### ISSUE TITLE
Fix link in documentation

### ISSUE THREAD

**Issue by electrical** [logstash-plugins/logstash-codec-netflow#1]
Currently there is a link to  https://github.com/logstash/logstash/tree/v2.0.0.dev/lib/logstash/codecs/netflow/netflow.yaml
this needs to be changed to the new repo.

**Comment by jsvd** [comment]
This now points to https://github.com/logstash-plugins/logstash-codec-netflow/blob/master/lib/logstash/codecs/netflow.rb#L33
