### ISSUE TITLE
Template length doesn't fit cleanly into flowset {:template_id=>257

### ISSUE THREAD

**Issue by VamPikmin** [logstash-plugins/logstash-codec-netflow#101]
- Version: logstash-codec-netflow-3.5.2
logstash 5.6.3
- Operating System: Ubuntu 16.04
- Config File:
` input {
    udp {
tags => ["netflow"]
type => "netflow"
port => 5046
    codec => netflow {
		 versions => [9]
	         }
        }

 output {
     if [type] == "netflow" {
 	 elasticsearch { hosts => ["http://localhost:9200"] }
         stdout { codec => rubydebug }	
         #file { path => "/log/netflow.log" }
	    }`

- Sample Data:
`[2017-10-19T07:52:24,549][WARN ][logstash.codecs.netflow  ] Template length doesn't fit cleanly into flowset {:template_id=>257, :template_length=>143, :record_length=>1392}`

- Steps to Reproduce:
Originally I was only collecting netflow for CISCO2901/K9
I'm not sure if this has started happening since I started ingesting the netflow from a cisco-wlc (5520) as well
I see it's a known issue because they might use the same template id?
People are working on logstash-input-netflow which might resolve the issue.
Since then I've removed the cisco-wlc netflow but the messages in the sample data still appear few times every minute

**Comment by jorritfolmer** [comment]
There have been some commits into the master branch that probably fix this issue.
Can you check if that is the case?

Steps:

1. `cd /home/you`
2. `git clone https://github.com/logstash-plugins/logstash-codec-netflow.git`
3. `vi /usr/share/logstash/Gemfile`
4. locate the line with `gem "logstash-codec-netflow" `
5. replace this line with `gem "logstash-codec-netflow", :path => "/home/you/logstash-codec-netflow"`
6. restart logstash

If that doesn't work, send me a pcap so I can take a look what's going on.

**Comment by VamPikmin** [comment]
Thank you kindly,
The template length error appears to be gone but I'm getting these in the log now:
[2017-10-20T09:12:28,841][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"logstash-2017.10.19", :_type=>"netflow", :_routing=>nil}, 2017-10-19T22:12:46.000Z 192.168.199.1 %{message}], :response=>{"index"=>{"_index"=>"logstash-2017.10.19", "_type"=>"netflow", "_id"=>"AV82seQicftdLdKJWw46", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [netflow.event_time_msec]", "caused_by"=>{"type"=>"json_parse_exception", "reason"=>"Numeric value (14340042958680621056) out of range of long (-9223372036854775808 - 9223372036854775807)\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@bd12cf9; line: 1, column: 455]"}}}}}

I've also added the Cisco Wireless Controller netflow which is on a different port
router port 5046
wlc port 5048
I am happy to send through the pcap, in case of sensitive information can I email you directly instead of pastebin?
Would I use something like this?
tcpdump udp port 5046 or port 5048 -w filename

**Comment by jorritfolmer** [comment]
The problem seems to be that Logstash sends an unsigned 64 bit value, while Elasticsearch expects a signed 64 bit value, which leaves a range of -2*63 to +2*63.

The expected value for a timestamp in msec would only yield a value of 1508578035000, which is 40 bit and expected to fit in a signed long. Even in nanoseconds it would only yield a 60 bit value.

Further questions that may lead you to a solution:
- find out why event_time_msec doesn't seem to emit epoch timestamp in milliseconds
- find out a way to accomodate unsigned 64 bit values in ES
- divide the value you're getting by 10000000 in Logstash, so you're actually getting milliseconds worth of timestamp.

**Comment by VamPikmin** [comment]
Thanks for that. I don't think I have enough understanding to figure it out on my own. Still fairly new to this, I have to spend time trying to learn the basics, the grok match statements as I've noticed most of mine result in _grokparsefailure even for syslog on Cisco switches. So I'm slowly trying to make sense of that first before I try to solve the issue here.
To stay on topic, the netflow stuff is still coming in from both the ASA and WLC but the warnings still show in the log

**Comment by VamPikmin** [comment]
Here's a pcap if you get a chance to have a look
[netflow.pcap.tar.gz](https://github.com/logstash-plugins/logstash-codec-netflow/files/1416762/netflow.pcap.tar.gz)

**Comment by jorritfolmer** [comment]
I've just replayed your pcap to the current codec version.
It decodes without any problems.
The Elasticsearch issue is something unrelated to the working of the codec, so I'm closing this issue.
