### ISSUE TITLE
Can I use logstash-codec-netflow to analysis sflow data ？

### ISSUE THREAD

**Issue by JasonLZJ** [logstash-plugins/logstash-codec-netflow#102]
Netflow Can only be used on CISCO devices，I have some switch devices which can send sflow data.
logstash can do that? How to do that?

thanks

**Comment by jorritfolmer** [comment]
Logstash-codec-netflow doesn't support sflow.

There was a logstash-codec-sflow some years back. I don't see it anymore on the Elastic site.
However, there appear to be some individual repositories available on Github.

**Comment by untergeek** [comment]
softflowd captures similar data and sends it in netflow format.  I've used that on my routers.

**Comment by JasonLZJ** [comment]
@untergeek Can sflowtool do the same thing?

**Comment by JasonLZJ** [comment]
@jorritfolmer @untergeek Thank you very much. I need to do traffic analysis on devices from different vendors. Do you have any technical solutions?

**Comment by jorritfolmer** [comment]
You could check out https://github.com/VerizonDigital/vflow
