### ISSUE TITLE
netflow codec doesn't seem to work with logstash 6.0.0

### ISSUE THREAD

**Issue by mwpv** [logstash-plugins/logstash-codec-netflow#109]
I have opened a thread on the elastic.co forums on this issues, however was able to validate with my configuration that it seems 6.0.0 logstash is not able to be loaded using the latest netflow codec. I had validated with a few known working 2.1.0 netflow configuration files procured from the IRC channel, however these would not load as well in logstash 6.0.0 Upon downgrading to 6.0.0 I can successfully use the netflow codec without issue.

**Comment by jorritfolmer** [comment]
Can you post the config?

**Comment by jorritfolmer** [comment]
And any errors in the log.

**Comment by jorritfolmer** [comment]
Or other stuff that will help in finding a root cause?

**Comment by mwpv** [comment]
@jorritfolmer  thanks for your replay but somehow we solved it!
