### ISSUE TITLE
Can't (yet) decode flowset id 266 from source id 0, because no template to decode it with has been received. This message will usually go away after 1 minute

### ISSUE THREAD

**Issue by szhong12** [logstash-plugins/logstash-codec-netflow#111]
Version: Logstash 6.0.0/logstash-codec-netflow 3.7.0
Operating System: Ubuntu16.04
Config File:
input {
    udp {
        port => 4739
		codec => netflow
    }
}
output {
	stdout {
		codec => "json_lines"
	}
}

Steps to Reproduce:
Start Logstash
View the logs
Receive the following warnings repeatedly:
[2017-12-04T17:50:08,205][WARN ][logstash.codecs.netflow  ] Unsupported field in template 266 {:type=>150, :length=>4}
[2017-12-04T17:50:08,214][WARN ][logstash.codecs.netflow  ] Unsupported field in template 292 {:type=>150, :length=>4}
[2017-12-04T17:50:08,216][WARN ][logstash.codecs.netflow  ] Can't (yet) decode flowset id 266 from source id 0, because no template to decode it with has been received. This message will usually go away after 1 minute.

**Comment by tim-timmer** [comment]
It seems you'll get this message until netflow source send the templates. With my ASA I had to wait about 10 minutes until this messages gone

**Comment by jorritfolmer** [comment]
@szhong12 can you post (or mail) a pcap?
It seems there is an unsupported field in template 266 and 292 that causes the template to be ignored.

**Comment by szhong12** [comment]
Thank you for your reply, this is my pcap file.
------------------ 原始邮件 ------------------
发件人: "Jorrit Folmer";<notifications@github.com>;
发送时间: 2017年12月17日(星期天) 晚上10:32
收件人: "logstash-plugins/logstash-codec-netflow"<logstash-codec-netflow@noreply.github.com>;
抄送: "阳光02"<503614084@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [logstash-plugins/logstash-codec-netflow] Can't (yet) decodeflowset id 266 from source id 0, because no template to decode it with hasbeen received. This message will usually go away after 1 minute (#111)




@szhong12 can you post (or mail) a pcap?
 It seems there is an unsupported field in template 266 and 292 that causes the template to be ignored.

**Comment by Noebas** [comment]
You need to set your asa to send the template, the template timeout setting to 1 min. the message will go away and logstash starts working after this

![image](https://user-images.githubusercontent.com/15727101/34420237-c81b1dc6-ec08-11e7-918a-21fda5a7dfbc.png)

**Comment by jorritfolmer** [comment]
Ok fixed in v3.9.1.
Thanks for the pcap!

**Comment by szhong12** [comment]
Thank you for your help!
When add a new device ,  I receive the following warnings repeatedly.
Can't (yet) decode flowset id 266 from observation domain id 262144, because no template to decode it with has been received. This message will usually go away after 1 minute.




------------------ 原始邮件 ------------------
发件人: "Jorrit Folmer";<notifications@github.com>;
发送时间: 2017年12月30日(星期六) 晚上9:54
收件人: "logstash-plugins/logstash-codec-netflow"<logstash-codec-netflow@noreply.github.com>;
抄送: "阳光02"<503614084@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [logstash-plugins/logstash-codec-netflow] Can't (yet) decodeflowset id 266 from source id 0, because no template to decode it with hasbeen received. This message will usually go away after 1 minute (#111)




Ok fixed in v3.9.1.
 Thanks for the pcap!
