### ISSUE TITLE
Netflow sent by Cisco ASA 9.6(1) doesn't contain IN_BYTES and IN_PACKETS

### ISSUE THREAD

**Issue by tim-timmer** [logstash-plugins/logstash-codec-netflow#112]
Hello!

Elasticsearch v6.0.0 + X-Pack
Logstash v6.0.0 + X-Pack
Kibana v6.0.0 + X-Pack
OS: Ubuntu 16.04.1 x86-64

The issue is that Cisco ASA 9.6(1) doesn't send IN_PACKETS and IN_BYTES fields - [ASA Netflow spec](https://www.cisco.com/c/en/us/td/docs/security/asa/special/netflow/guide/asa_netflow.html). For bytes count it sends the following fields:
NF_F_FWD_FLOW_DELTA_BYTES - The delta number of bytes from source to destination.
NF_F_REV_FLOW_DELTA_BYTES - The delta number of bytes from destination to source.
and no data for packets count.
Any ideas how to update templates and dashboards?
Pcap is attached.
[netflow-12055.zip](https://github.com/logstash-plugins/logstash-codec-netflow/files/1538060/netflow-12055.zip)

**Comment by rol-ubiqube** [comment]
Hi, as that information is available in Cisco ASA 9.8 and was doubting 9.6 didn't have it, I just did a quick check in your pcap, and yes it is available.
You can see this in flowset id = 0 (template) for template id 263 - fields 18 (initiatorOctets) and 19 (responderOctets).
And it's only necessary to use the correspondent 231 and 232 of netflow codec.
Regards

**Comment by jorritfolmer** [comment]
Closing this issue, as @rol-ubiqube pointed out the bytes field in the pcap. Thanks for taking a look btw!

**Comment by acheraime** [comment]
Was his issue resolved? I have the same problem running ASA 9.1.

**Comment by rol-ubiqube** [comment]
@acheraime either in ASA 9.1 documentation or ideally in pcap, you should check if the required fields are available (as per my previous comment - https://github.com/logstash-plugins/logstash-codec-netflow/issues/112#issuecomment-351767160.
