### ISSUE TITLE
NEW Performance processing issue - Cisco ASA 9.8 netflows

### ISSUE THREAD

**Issue by rol-ubiqube** [logstash-plugins/logstash-codec-netflow#117]
I'm raising this issue, after having read the issue below, and not being even close of reaching the referred performance figures.
https://github.com/logstash-plugins/logstash-codec-netflow/issues/85

Version: logstash 5.6.5 / logstash-codec-netflow 3.8.3
Operation System: CentOS release 6.8 (Final)
Config files:
------------------
netflow.conf (just added metric filter and output to be able to measure the flows per second processed - metric output file being written into /tmp)
------------------
input {
	udp {
		type => "netflow"
		port => 9995
		receive_buffer_bytes => 16777216
		workers => 8
		codec => netflow {
			versions => [5,9]
			cache_save_path => "/tmp"
		}
	}
}

filter {
	metrics {
		meter => "events"
		add_tag => "metric"
	}
}

output {
	if "metric" in [tags] {
		file {
			path => "/tmp/test-%{+YYYY-MM-dd}.txt"
			codec => line {
			format => "1m rate | %{@timestamp} | %{[events][rate_1m]} | %{[events][count]}"
			}
		}
	}
}
-----------------------------
jvm.options
-----------------------------
-Xms8g
-Xmx8g
-----------------------------
logstash.yml - just changed batch size and adjusted jvm heap size as above to cope with big batches
pipeline.batch.size: 1000
-----------------------------
OS - parameter updated as per receive_buffer_bytes netflow configuration
net.core.rmem_max = 16777216
-----------------------------

For the tests, I'm using a real pcap from Cisco ASA (9.8) and I'm using an in-house simulator to send packets at 120 packets per second => 1920 flows / s (average 16 flows per packet).
In my opinion the simulator can be discard as a possible cause, because this finishes its work at the right rate and then logstash/netflow keeps processing the buffered packets in the background at a much slower rate.
The frustrating max rate I can see is 830 flows / sec for the above configuration.
Some additional and important (i think) information I can provide is:
1) the VM doesn't seem to be saturated, neither in terms of CPU (40% idle) nor in terms of memory, which for me makes sense. 
2) if I replace codec netflow by plain codec, I'll see the expected packets / sec rate in the metrics, so from this I believe the issue might be really related with the netflow codec.

Does anyone have faced this issue before, or does anyone have a clue on what can be the root cause or how to troubleshoot further?

**Comment by Noebas** [comment]
I'am seeing poor performance with ASA to but different behavior as described by you.
The input udp is using 100% cpu, always. with 1 working using 1 core, with 4 workers user 4 cores 100%

Not sure why this is taking all cpu and also not clear why dubbeling the cores is not dubbeling the flow processed but there wa was en similar case with Palo Alto in this case https://github.com/logstash-plugins/logstash-codec-netflow/issues/85

I did read en tryed al the tweaks form that case but no luck

![image](https://user-images.githubusercontent.com/15727101/34431422-5d927ea6-ec6f-11e7-9894-f6a0c377aa63.png)

**Comment by rol-ubiqube** [comment]
Hi @Noebas 
I also get 100% of CPU used if I increase the number of workers, or in some other tests I did with lower number of CPUs (and lower number of workers), but reading #85 and others I believe 16 vCPU will be required anyway for a throughput of 6400 flows/sec (which is the ASA throughput I can see - 400 packets / sec ; 16 flows / packet).
So, with 16vCPU and 8 workers CPU is not saturated as I mention in my previous comment.
Suggest that you configure 4vCPUs / 1 worker, expect that CPU is not saturated in that situation, and it will be easier to discuss why 1 worker doesn't achieve the >1000 flows / sec that it should, as per #85.

**Comment by jorritfolmer** [comment]
In issue #85 I included a benchmark but failed to specify the number of workers used on the 40 CPU dedicated AWS box. It should read:

| vCPU | UDP workers | flows/sec
|-----|---|------
|1 | 1| 2300
|2 | 2| 4300
|4| 4| 6700
|8| 8| 9100
|16| 16| 15000
|32 | 32| 16000

1) You should increase the amount of workers with the amount of vCPUs available
2) You should make sure that these vCPU's are actually available/reserved without oversubscription in the hypervisor
3) A number of concurrency issues have been fixed that were causing frequent crashes. These fixes however reduce performance at the expense of stability. Reading the additions by @jasonkeller to issue #91 it seems these aren't entirely fixed yet.
4) I haven't had time to redo the above benchmark with a current version of the plugin that contain the fixes.

**Comment by rol-ubiqube** [comment]
Thanks @jorritfolmer for the updated/completed benchmark, but the real numbers I'm getting are very far (less than 10%) from the benchmark you provide.
Fyi, to be sure it was not an oversubscription issue I've even repeated my tests in a physical device and figures I got were identical.
So, I'm really running out of options here and would appreciate hints on what else can be verified / double checked to identify the root cause of the bottleneck.

**Comment by rol-ubiqube** [comment]
@jorritfolmer Reading again #85 and specifically comment of https://github.com/logstash-plugins/logstash-codec-netflow/issues/85#issuecomment-320756806, I am now thinking that your benchmark might not be valid as well for Cisco ASA which loads a big number of different flow sets per packet. (12 in the example below, but I'say can even go up to 16 - in my production pcap I get 13-16 flows per packet and aggregation in different flowsets varies).

Fyi, tried your netflow_bench.py script, and i'm getting higher figures (roughly x5 flows/sec). For sure some stuff can be tuned e.g. logstash and jvm parameters, but this big improvement makes me really think that improvements might be required in the netflow codec so that this can cope with Cisco ASA netflow structure and its high throughputs.
I wouldn't say as in #85 that the lack of bundling in the Cisco ASA netflow package structure is bad practise, as I some see bundling (a couple of flows bundled in the in the same flowset).

@jorritfolmer I will continue investigating this further, but would appreciate if you can share your view and ideally benchmark netflow codec for cisco asa.
 
------------------------------------
Cisco NetFlow/IPFIX
    Version: 9
    Count: 13
    SysUptime: 4274927.699000000 seconds
    Timestamp: Dec 13, 2017 13:14:13.000000000 GMT Standard Time
    FlowSequence: 1375470064
    SourceId: 0
    FlowSet 1 [id=265] (1 flows)
    FlowSet 2 [id=263] (1 flows)
    FlowSet 3 [id=265] (1 flows)
    FlowSet 4 [id=263] (1 flows)
    FlowSet 5 [id=265] (1 flows)
    FlowSet 6 [id=256] (1 flows)
    FlowSet 7 [id=263] (1 flows)
    FlowSet 8 [id=265] (1 flows)
    FlowSet 9 [id=263] (1 flows)
    FlowSet 10 [id=265] (1 flows)
    FlowSet 11 [id=260] (2 flows)
    FlowSet 12 [id=263] (1 flows)
------------------------------------

**Comment by danuuk** [comment]
Hello! I have the similar issue with Cisco ASA flow data. With **workers => 16** (no filtering and output to Null) I can only reach ~1200 flows/sec. I run logstash on dedicated server with 16 cores and during the test almost all of them saturated.

**Comment by jorritfolmer** [comment]
Performance impact for the concurrency fixes are -20%.
This is from a quick benchmark on my i7 laptop.

Processing Cisco ASR 9000 router flows:

| vCPU | UDP workers | v3.4.0 flows/sec | v3.10.0 flows/sec
|-----|---|------|---
|2 | 2| 3040 | 2470

Processing Cisco ASA firewall flows is 3x slower than Cisco ASR flows:

| vCPU | UDP workers | v3.4.0 flows/sec| v3.10.0 flows/sec
|-----|---|------|---
|2 | 2| not tested | 770

I've updated the documentation to reflect these realities.

**Comment by jorritfolmer** [comment]
I've also commited two new standalone benchmark script in the spec/codec directory:
- `netflow_bench_cisco_asa.py`: sends 210000 Cisco ASA firewall flows
- `netflow_bench_cisco_asr.py`: sends 210000 Cisco ASR 9000 router flows

**Comment by rol-ubiqube** [comment]
@jorritfolmer I've tried the "netflow_bench_cisco_asa.py" script, and checking pcap don't think this is representative of real Cisco ASA netflow traffic.
As per my previous comment, what I see on real pcap from Cisco ASA is several flowsets (see details on https://github.com/logstash-plugins/logstash-codec-netflow/issues/117#issuecomment-355580025) and in your python script you have 14 flows within one single flowset.
This said, I don't think the 770 flows/sec (2vCPU, 2 UDP workers) can be considered a benchmark for Cisco ASA.
Would it be possible that you provide a benchmark script for Cisco ASA, as per the example structure included in my previous comment?

**Comment by jorritfolmer** [comment]
No sorry I need pcaps for that.

**Comment by rol-ubiqube** [comment]
@jorritfolmer please find attached pcap from test ASA.
Note that this sample pcap has 6 flowsets (containing one flow each) but as per the structure included in my previous comment (https://github.com/logstash-plugins/logstash-codec-netflow/issues/117#issuecomment-355580025) the number of flowsets can be definitely higher, so suggest for benchmarking a python script is prepared with 12 flowsets, some with 2 or 3 flows - to total of 16 flows (using at least 5 different flow templates).

[ASA_sample_pcap.zip](https://github.com/logstash-plugins/logstash-codec-netflow/files/1678722/ASA_sample_pcap.zip)

**Comment by jorritfolmer** [comment]
Ah but I need those exact flowsets in various packets for me to create a benchmark script from. I can't synthesise them from small fragments.

**Comment by rol-ubiqube** [comment]
@jorritfolmer in my opinion you should be able to synthesize them from the template packet, where are templates are defined.
But on the hand, I can suggest that you create a benchmark script with 12 flowsets (each with 1 flow) - 6 of the flows for template 263 and other 6 for template 265 (both of these are in the pcap I provided).

**Comment by jorritfolmer** [comment]
Apologies but I don't have the time nor the tools to synthesise packets to your specification.

**Comment by rol-ubiqube** [comment]
ok, understand, but note that these not my specifications, and just ASA netflow packet structure.
I'd just appreciate your confirmation to my belief that your current ASA benchmark cannot be considered valid, because ASA real netflow packet structure is very different than the used in your netflow_bench_cisco_asa.py script.

**Comment by jorritfolmer** [comment]
I think the fact that we're having this discussion is proof enough that the ASA benchmark script cannot be considered valid (yet) for the purposes of getting a realistic flows/sec metric.

However for the purposes of validating performance improvements to the code I think it's fine.
For example I'm suspecting the asa_acl_id field to be responsible for the 3x loss in performance compared to flows without. The current asa benchmark script gives us a tool to validate this hypothesis, and help guide optimisations to the code handling asa_acl_id fields.

Perhaps we should revisit the goal of benchmark realism after we have achieved this first optimisation.

**Comment by jorritfolmer** [comment]
I've release v3.11.1 with performance improvements for:
- decoding ASA ACL id 
- decoding mac addresses

Can you see what this does for your performance?

**Comment by rol-ubiqube** [comment]
@jorritfolmer is v3.11.1 compatible with logstash 5.6.5?

**Comment by jorritfolmer** [comment]
Yes I've tested it with 5.6.4 and 6.0.0.
I'm not sure what's wrong with the Travis build for 5.6.x, for now I assume it's unrelated to this codec.

**Comment by jorritfolmer** [comment]
I've release v3.11.2 with further performance improvements.

**Comment by jorritfolmer** [comment]
netflow-bench-cisco-asr.py:

| vCPU | UDP workers | v3.4.0 | v3.10.0 | v3.11.2 
|-----|---|------|------|---
|2 | 2| 3040 | 2470 | 2700

netflow-bench-cisco-asa.py:

| vCPU | UDP workers | v3.4.0 | v3.10.0 | v3.11.2
|-----|---|------|------|---
|2 | 2| not tested | 770 | 1900
