### ISSUE TITLE
[WARN ][logstash.codecs.netflow  ] Invalid netflow packet received (End of file reached) [2018-01-10T11:00:18,439][WARN ][logstash.codecs.netflow  ] Ignoring Netflow version v210 [WARN ][logstash.codecs.netflow  ] Can't (yet) decode flowset id 45841 from observation domain id 0, because no template to decode it with has been received. This message will usually go away after 1 minute.

### ISSUE THREAD

**Issue by manjing** [logstash-plugins/logstash-codec-netflow#119]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version:
- Operating System:
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

**Comment by jorritfolmer** [comment]
Sorry but you're posting 3 different issues without any further information.
Closing.
