### ISSUE TITLE
Netflow Codec cannot handle V9 Template record

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-codec-netflow#12]
(This issue was originally filed by @haybeseret at https://github.com/elastic/logstash/issues/2002)

---

Hi,
I am using logstash netflow codec.
While generating only 1 flowset in a packet (i.e data flow set) everything work as expected.
When i am generating 2 flowsets in a packet Data+ template as per rfc3954, it seem that the logstash coded cannot handle the template flowset
image below show the 2 flowset in a a packet which the netflow codec cannot parse.
I am getting the following error

"Unsupported field {:type=>225, :length=>4, :level=>:warn}
No matching template for flow id 256 {:level=>:warn}"

![netflow1](https://cloud.githubusercontent.com/assets/5445223/4874714/d53ae8b2-626b-11e4-9444-f8c2a80ac00c.png)

**Comment by bodgit** [comment]
It's not the number of flowsets, your data template includes a field that Logstash doesn't understand.

Template ID 256 contains a field of type 225 which Logstash doesn't know about (the first error) so it can't build a parser for any subsequent Data flowset using that template ID (the second error).

You need to either define that field type with a suitable data type and field name:
```yaml
225:
- :uint32
- :name_of_field
```
Or mark it to be skipped:
```yaml
225:
- :skip
```
There may be subsequent field types, it short circuit fails on the first unknown field type, expanding the "Template (Id = 256, Count = 18)" line would show all the field types in the template.

**Comment by missnebun** [comment]
Hi Guys,

I have the same problem .... not sure what is going on ... Was working until I restart logstash now I  see lots of  
{:timestamp=>"2015-07-06T14:26:42.686000-0400", :message=>"No matching template for flow id 256", :level=>:warn}
Messages and no data .... I do not see any other error or warning. I reinstall netflow codec ... still same problem.

**Comment by wrigby** [comment]
@missnebun How often are your flow exporters (routers) configured to send out template records? When Logstash starts, it will have to wait for a template record before it can parse the flowset records. If those messages are lasting more than a minute or so, then we have a real problem.

**Comment by missnebun** [comment]
wrigby Thank you. I figure that out at some point. I check the netflow traffic with tshark -ni bond0 -R udp.port==9995 -d udp.port==9995,cflow -V and I was getting the template records every hour. I ask the network group to change that. Now looks like is working fine. 

Regards,
Gabriel

**Comment by zhaohangbo** [comment]
Why can't I parse the netflow data and write the data to file.
Although I can capture the netflow template(256,263) and data flowset via TShark successfully.

But why it keeps report warnings in the log.
```
No matching template for flow id 256,263
Unsupported field type=xxx length xxx
```

**Comment by jorritfolmer** [comment]
In summary: the original issue refers to an unsupported field type 225 which is most likely a field from Cisco ASA. Support for Cisco ASA fields has been added with the recent merger of PR #24.
