### ISSUE TITLE
logstash not working for Huawei Netstream

### ISSUE THREAD

**Issue by zwirk** [logstash-plugins/logstash-codec-netflow#121]
Hi, Team

Please, make support of Huawei netstream.

**Comment by jorritfolmer** [comment]
Can you provide a pcap with netflow from this device?

**Comment by zwirk** [comment]
Hello

I added files to this post.

[huawei_netstream.pcap.txt](https://github.com/logstash-plugins/logstash-codec-netflow/files/1673435/huawei_netstream.pcap.txt)

[hardware.txt](https://github.com/logstash-plugins/logstash-codec-netflow/files/1673429/hardware.txt)

[logstash-plain.log](https://github.com/logstash-plugins/logstash-codec-netflow/files/1673430/logstash-plain.log)

Thank

**Comment by jorritfolmer** [comment]
Thanks, the latest version (3.11.0) now supports Huawei Netstream!
I will release this version in a few minutes.
