### ISSUE TITLE
Implement IPFIX reduced size encoding support (Was: Template length exceeds flowset length)

### ISSUE THREAD

**Issue by antiuser** [logstash-plugins/logstash-codec-netflow#123]
In logs i see huge repeatedly messages:
`[WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"elastiflow-2018.02.18", :_type=>"doc", :_routing=>nil}, #<LogStash::Event:0x73a7b610>], :response=>{"index"=>{"_index"=>"elastiflow-2018.02.18", "_type"=>"doc", "_id"=>"MByGp2EBu08NUWC7JEYT", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [netflow.tcpOptions]", "caused_by"=>{"type"=>"json_parse_exception", "reason"=>"Numeric value (17293822569104482748) out of range of long (-9223372036854775808 - 9223372036854775807)\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@119006d0; line: 1, column: 1761]"}}}}}` 

`[WARN ][logstash.codecs.netflow  ] Template length exceeds flowset length, skipping {:template_id=>260, :template_length=>65, :record_length=>64}`

and somewhat less often this messages:
`[WARN ][logstash.codecs.netflow  ] Received template 260 of size 61 bytes doesn't match BinData representation we built (65 bytes)`
`[WARN ][logstash.codecs.netflow  ] Received template 263 of size 49 bytes doesn't match BinData representation we built (53 bytes)`
`[WARN ][logstash.codecs.netflow  ] Template length exceeds flowset length, skipping {:template_id=>263, :template_length=>53, :record_length=>52}`

- logstash 6.2.1 / logstash-codec-netflow (3.11.2):
- Debian 8.10 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02):
- Device ipt_NETFLOW master branch (https://github.com/aabc/ipt-netflow)
- Run Logstash and view the log file

Tshark pcap dump in attach.
Thanks a lot!
[tshark.zip](https://github.com/logstash-plugins/logstash-codec-netflow/files/1734440/tshark.zip)

**Comment by antiuser** [comment]
Temporary fixed by skipping tcpOptions in 
`/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.11.2/lib/logstash/codecs/netflow/netflow.yaml`
But, this is not a solution

**Comment by jorritfolmer** [comment]
For template 260 and 263 it seems ipt_NETFLOW sends Netflow field 209 as 4 bytes whereas it should be an 8 byte field as per [IANA specs](https://www.iana.org/assignments/ipfix/ipfix.xhtml).
Since we use this 8 byte specification in netflow.yaml, there is a size mismatch and decoding fails.

You should create an issue with ipt_NETFLOW.

**Comment by antiuser** [comment]
check this please [here](https://github.com/aabc/ipt-netflow/issues/97)

**Comment by jorritfolmer** [comment]
Ah thanks for the pointer!
