### ISSUE TITLE
Netflow extra fields / Unsupported field in template

### ISSUE THREAD

**Issue by crycookie** [logstash-plugins/logstash-codec-netflow#125]
I have latest ELK 6.2.2, CentOS 7. 
We are sending netflow data from ntop with custom http fields. 

I receive following errors: 
[WARN ][logstash.codecs.netflow  ] Unsupported field in template 258 {:type=>57652, :length=>128}
[WARN ][logstash.codecs.netflow  ] Can't (yet) decode flowset id 258 from source id 96, because no template to decode it with has been received. This message will usually go away after 1 minute.
I've checked the pcap, and there's description for # 258 template. 
![image](https://user-images.githubusercontent.com/33386975/37039339-4651ba4e-2168-11e8-976f-c6b0e9163948.png)
However, there's no reference in netflow.yaml for those extra fields and seems like 258 is already in use:
258:
- :uint64
- :collectionTimeMilliseconds

  I've tried to add following, but no luck:
57652:
- :string
- :http_url
57653:
- :uint8
- :http_ret_code
57654:
- :string
- :http_referer
57655:
- :string
- : http_ua
57659:
- :string
- :http_host

So, the question is how do I add extra fields? what's the syntax? 
Thanks in advance.

**Comment by crycookie** [comment]
Idk what happened, but adding descriptions for extra fields one by one fixed the issue. After that killing the ES index restarting logstash gives me what I need.

**Comment by jorritfolmer** [comment]
What kind of device is this Netflow from?
Do you think it should be included by default in this codec?
If so can you share a small pcap, so I can add it to our test repository?
