### ISSUE TITLE
pfflowd: Can't (yet) decode flowset id 259 from source id 0, 

### ISSUE THREAD

**Issue by poggenpower** [logstash-plugins/logstash-codec-netflow#126]
For all general issues, please provide the following details for fast resolution:

- Version: logstash                                   1:6.2.3-1
- Operating System: Ubuntu 1710
- Config File 
input {  
  tcp {
    type => "syslog"
    port => 5140
  }
}
#udp syslogs tream via 5140
input {  
  udp {
    type => "syslog"
    port => 5140
  }
}
input {
   udp {
     port => 2055
     codec => netflow
     type => "netflow"
   }
}
output {  
  if "_grokparsefailure" in [tags] {
    file { path => "/var/log/logstash/failed_syslog_events-%{+YYYY-MM-dd}" }
  }
  if "_clone" in [tags] {
    file { path => "/var/log/logstash/clones-%{+YYYY-MM-dd}" }
  }
  if "_jsonparsefailure" in [tags] {
    file { path => "/var/log/logstash/failed_json_events-%{+YYYY-MM-dd}" }
  }
  if "_clone" not in [tags] {
    if "netflow" in [tags] {
      elasticsearch { 
	hosts => ["localhost:9200"]
	index => "netflow-%{+YYYY.MM.dd}" 
      }
      file { path => "/var/log/logstash/netflow-%{+YYYY-MM-dd}" }
    } else {
      elasticsearch { 
	hosts => ["localhost:9200"]
	index => "logstash-%{+YYYY.MM.dd}" 
      }
    }
  }  
  # stdout { codec => rubydebug }  
}

- Sample Data: 
[netflow.pcap.zip](https://github.com/logstash-plugins/logstash-codec-netflow/files/1855558/netflow.pcap.zip)

- Steps to Reproduce:
Sending data from Opnsense 18.1.5 which is effectively a pflowd.
See attached pcap. Templates are send out. 
The logstash log gives:
`[2018-03-28T01:34:23,201][WARN ][logstash.codecs.netflow  ] Can't (yet) decode flowset id 259 from source id 0, because no template to decode it with has been received. This message will usually go away after 1 minute.`
continuously, but there are no other errors complaining about the template format, like I have seen in other cases.

**Comment by jorritfolmer** [comment]
Can you try upgrading the codec to the most recent version 3.11.4? I suspect you experience the same issue as #122 for which we introduced a fix in the latest version.

**Comment by poggenpower** [comment]
Hello Jorrit,
thanks, found out, that the template is not send as regular as expected. It needs sometimes 10 minutes until it is send. 
By random I did my network capture in the minute the template was send. 
Bye
 Thomas
