### ISSUE TITLE
netflow codec and "Cannot find Serializer for class" issue

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-codec-netflow#13]
(This issue was originally filed by @tomarch at https://github.com/elastic/logstash/issues/2667)

---

i use lastest logstash 1.5.0 beta1 and elasticsearch 1.4.4
I have an issue when using netflow codec

here's my logstash config :  https://gist.github.com/tomarch/d824d5781a725cf68a10

I've got an error when i use elasticsearch or file output: Got error to send bulk of actions to elasticsearch server at localhost : Cannot find Serializer for class: org.jruby.RubyObject {:level=>:error}

The complete error log for the elasticsearch output : https://gist.github.com/tomarch/3f16b02100717681242d

The stdout seems fine : https://gist.github.com/tomarch/dc3f0561b473d0542dcd

**Comment by bodgit** [comment]
I think this might have been fixed by #8.
