### ISSUE TITLE
IPFIX unsupported enterprise 15397

### ISSUE THREAD

**Issue by abeeson** [logstash-plugins/logstash-codec-netflow#130]
The IPFIX module is missing support for NetIntact/Procera/Sandvine ID 15397.

I'm in the process of adding these to the IPFIX yaml file and I'll put a pull req up once I'm done, but I'm not sure how to handle a few data types.

I've got signed 32bit integers and 32 bit floats for a few fields, should they be int32 and float32? I couldn't find any examples in the yaml already and i wanted to make sure it was 100% right.

Let me know when you can and I'll ensure my pull req has them correctly put in.

Thanks!
Ayden

**Comment by abeeson** [comment]
Added in https://github.com/logstash-plugins/logstash-codec-netflow/pull/131 with standard types as above. Let me know via the PR if i need to change anything.

**Comment by jorritfolmer** [comment]
Merged. Thanks again for your contribution
