### ISSUE TITLE
Add support for Barracuda IPFIX "Extended Uniflow"

### ISSUE THREAD

**Issue by robcowart** [logstash-plugins/logstash-codec-netflow#132]
OS: Ubuntu Server 16.10
Logstash: 6.2.3
Codec: 3.12.0

Receiving IPFIX "Extended Uniflow" from Barracuda devices. I am receiving this message, which I assume indicates an issue processing the template:

[2018-04-18T10:25:47,230][WARN ][logstash.codecs.netflow  ] Unsupported enterprise {:enterprise=>10704}

Obviously with no template processed there are a lot of these messages:

[2018-04-18T10:25:47,231][WARN ][logstash.codecs.netflow  ] Can't (yet) decode flowset id 256 from observation domain id 0, because no template to decode it with has been received. This message will usually go away after 1 minute.

I am attaching a PCAP which contains a number of flows as well as a template packet.

[barracuda_extended_uniflow.pcap.zip](https://github.com/logstash-plugins/logstash-codec-netflow/files/1923207/barracuda_extended_uniflow.pcap.zip)

It would be great is support could be added for this record type. Thanks.

**Comment by jorritfolmer** [comment]
Can you provide docs that specify which fields are which?

**Comment by robcowart** [comment]
This is all I could find...

https://campus.barracuda.com/product/cloudgenfirewall/doc/73719598/how-to-configure-audit-reporting-with-ipfix/?sl=AWMBowQkKXZVtIOC3fD6&so=4

**Comment by jorritfolmer** [comment]
Ok thanks that works!
I've added support in the most recent commit.
New release early next week.

**Comment by robcowart** [comment]
Great! Thanks! I will test the new release and provide feedback here.
