### ISSUE TITLE
Reduced-size encoding for uint32 is larger than uint32

### ISSUE THREAD

**Issue by dfdalamar** [logstash-plugins/logstash-codec-netflow#136]
Hi,

I am using Logstash 6.2.4 on Ubuntu server 16.04.  I am using the base netflow module and I am getting this error.

[2018-05-03T12:57:47,415][WARN ][logstash.codecs.netflow ] Reduced-size encoding for uint32 is larger than uint32 {:field=>[:uint32, :rev_flow_delta_bytes], :length=>8}

I saw when I did a search that there was a possible fix by editing a lib/logstash/codec/netflow.rb file.  However I do not have that file.  The only netflow config file I have is located at /usr/share/logstash/modules/netflow/configuration/logstash/netflow.conf.erb.

I could not find anything referenced in that file that looked like what I saw in the fix I found.  Can someone assist me?

**Comment by dfdalamar** [comment]
Oh cool!!!!   Thank you!!!!

**Comment by jorritfolmer** [comment]
Ok done v3.13.2 is out
