### ISSUE TITLE
netflow codec support for IPFIX

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-codec-netflow#14]
(This issue was originally filed by @gonrada at https://github.com/elastic/logstash/issues/3143)

---

I was wondering if the current netflow codec would/could support decoding IPFIX flow rather than netflow v5/9.
Unless I am mistaken, wouldn't it be as simple as updating [/lib/logstash/codecs/netflow/netflow.yaml](https://github.com/elastic/logstash/blob/v1.4.2/lib/logstash/codecs/netflow/netflow.yaml) with the values from http://www.iana.org/assignments/ipfix/ipfix.xml?

I did find this ticket wanting a ipfix input plugin https://github.com/elastic/logstash/issues/2525, however I feel that with the tcp input plugin and the netflow codec this could be accomplished without an additional input plugin.

**Comment by bodgit** [comment]
See #10.

**Comment by gonrada** [comment]
Not sure if this ticket is necessary since [#10](https://github.com/logstash-plugins/logstash-codec-netflow/pull/10) is open. Should closed as a dup?

**Comment by jorritfolmer** [comment]
IPFIX support has been merged into master now
