### ISSUE TITLE
A bug in v3.14.0

### ISSUE THREAD

**Issue by JasonLZJ** [logstash-plugins/logstash-codec-netflow#141]
I update the plugin to v3.14.0 in order to resolve my h3c device. #140 

I found an error after running for a while.

I save the log:

![image](https://user-images.githubusercontent.com/4046183/40343690-af99d0a8-5dc3-11e8-8613-b36076f8d332.png)

when the error occur, the plugin stopped working.

thanks @jorritfolmer

**Comment by jorritfolmer** [comment]
Thanks! Fixed in 3.14.1.
