### ISSUE TITLE
Add support for MPLS labels

### ISSUE THREAD

**Issue by JasonLZJ** [logstash-plugins/logstash-codec-netflow#153]
I send netflow v9 packets to logstash
The pacp file is [this](https://github.com/JasonLZJ/netflow_for_h3c/blob/master/test.pcap) 
Can you help me? 

thanks

**Comment by jorritfolmer** [comment]
Thanks for the pcap, I'll look into it later.
Are you running the latest version of the codec?
What network device do you use to send Netflow9?

**Comment by JasonLZJ** [comment]
hi @jorritfolmer ：
  my device  use to send netflow9.
  my netflow codec is logstash-codec-netflow (3.14.1)

**Comment by JasonLZJ** [comment]
hi @jorritfolmer  I update it to 4.1.1 
The problem is not solved.
thx

**Comment by JasonLZJ** [comment]
hi @jorritfolmer 
Can you give priority to it? We rely on this service more. Thank you very much.

**Comment by JasonLZJ** [comment]
hi @jorritfolmer  I find the log
Unsupported field in template 1317 {:type=>70, :length=>3} 

thanks

**Comment by robcowart** [comment]
Your PCAP includes templates 1315, 1317, 1319 & 1320. However it only include flow records for 1315. Can you provide a PCAP that has flow records for all four flowsets?

**Comment by robcowart** [comment]
@janniten your's is a different issue related to IXIA IPFIX records. This issue is for Huawei.

**Comment by janniten** [comment]
Oki! Thank you!

**Comment by robcowart** [comment]
@JasonLZJ are you able to provide a more complete PCAP as I requested above. I have this fix largely completed, but I need the PCAP to confirm all is as intended.

**Comment by jorritfolmer** [comment]
So this appears to be first time in years that we finally encounter fields 70-79 MPLS labels in Netflow v9! And we *almost* have a complete pcap!

**Comment by jorritfolmer** [comment]
There is a closed PR #5 from 2 years ago that we can re-use

**Comment by robcowart** [comment]
#5 looks like it would handle the unpacking of the MPLS labels. However, the other issue with the Huawei Netflow records is that they use a `uint32` for interface index values (similar to IPFIX), where Netflow (v5 or v9) specifies a `uint16` for these values.

From the template ...
```
Field (9/25): INPUT_SNMP
    Type: INPUT_SNMP (10)
    Length: 4
Field (10/25): OUTPUT_SNMP
    Type: OUTPUT_SNMP (14)
    Length: 4
```

**Comment by JasonLZJ** [comment]
I caught more packages for the community.   [mpls](https://github.com/JasonLZJ/netflow_for_h3c/blob/master/mpls.pcap)

@robcowart 

thanks

**Comment by jorritfolmer** [comment]
Your pcap still only contains data packets for template 1315.
The MPLS ones are 1317 and 1319.

Traffic with template 1315 is getting decoded properly.
All your traffic uses template 1315.

I don't think you are actually missing/losing data.
You're seeing an error message, but it doesn't affect your netflow data.

**Comment by JasonLZJ** [comment]
My application only needs to parse 1315 packets.

Do you mean that I can parse 1315 packets without upgrading the version of plugin ?
@jorritfolmer 

thanks

**Comment by jorritfolmer** [comment]
Yes Huawei flows with template 1315 have been supported since 3.11.0.
