### ISSUE TITLE
Issue with Nokia 7750

### ISSUE THREAD

**Issue by rajjaisur** [logstash-plugins/logstash-codec-netflow#156]
I am having issue with Nokia 7750
Operating System : Debian9
netflow version - 9
logstash version. 6.3
logstash-codec-netflow (4.1.0)
netflow_cache_file_output : 
{"0|256":[["uint32","scope_system"],["uint8","sampling_algorithm"],["uint32","sampling_interval"]]}

logstash error : 
netflow - Can't (yet) decode flowset id 257 from source id 0, because no template to decode it with has been received. This message will usually go away after 1 minute.

**Comment by jorritfolmer** [comment]
I'll look into this later, I've got your pcap file in the mail, thanks.

**Comment by rajjaisur** [comment]
Thank you for your reply.
Actually issue is solved.
after debugging 
Nokia 7750 was sending.
Type: multicastReplicationFactor (99)
which was missing on netflow.yaml, So I have added below line in netflow.yaml

99:
- :uint32
- :multicastReplicationFactor

and it worked.
Thanks

**Comment by jorritfolmer** [comment]
Can I add 1 packet from your pcap to our collection of known working exporters?
Or does it contain production flows that need to be sanitized?

**Comment by rajjaisur** [comment]
yes, you can
