### ISSUE TITLE
Templates seem to be worker specific...

### ISSUE THREAD

**Issue by robcowart** [logstash-plugins/logstash-codec-netflow#159]
I was comparing a few different environments and noticed issues with the 4.1.x versions of the codec. The number of flows was only a few/sec, and netstat showed no UDP packet loss so that was not the issue.

The 4.1.x instances were producing significantly fewer flows than the 4.0.x and earlier instances. The logs of the 4.1.x instances also always showed `Can't (yet) decode flowset id...` messages although some flows of the indicated flowset ids did make it through.

It is as if the UDP input worker that first processed the template had access to it, but no other workers do. So some flows are decoded and passed to the pipeline, and the others are always dropped.

Installing v4.0.2 of the codec fixes the problem and works fine, and was confirmed in multiple environments. I think it may have been https://github.com/logstash-plugins/logstash-codec-netflow/commit/e9575ef039d29cf877107601111f043f61acd4af which introduced the issue.

To test this make sure to use multiple UDP input workers.

**Comment by yaauie** [comment]
@robcowart I've identified the issue and created a PR to address (#160).

This was my fault. In refactoring the template registry into its own class, I failed to pass the `@ttl` of the `TemplateRegistry` through to the volatile hashes that stored the templates, allowing the `Vash` default of 60s to win.

**Comment by jorritfolmer** [comment]
Ok merged in master.
Release will follow when I have some more time.

**Comment by jsvd** [comment]
@jorritfolmer I created a PR to bump the version and edit the changelog, let me know if this is ok with your standards https://github.com/logstash-plugins/logstash-codec-netflow/pull/161

**Comment by jorritfolmer** [comment]
Yep, thanks! I've just pushed the 4.1.2 gem to rubygems
