### ISSUE TITLE
Can't decode flowset - IPFIX from IXIA packet broker

### ISSUE THREAD

**Issue by janniten** [logstash-plugins/logstash-codec-netflow#163]
For all general issues, please provide the following details for fast resolution:

- Version: 6.3.2
- Operating System: Redhat
- Config File (if you have sensitive info, please remove it):
input {
  udp {
    port => "4001"
    codec => netflow {
                versions => 10
                cache_save_path => "/tmp/netflow_template"
                include_flowset_id => true
                cache_ttl => 999999999
    }
    type => "ipfix"
  }
}

Hi, I'm trying to ingest netflow data from IXIA packet broker into elastic, but it seems that the plugin cannot find the template  in the traffic.
I've aldready verify using a wireshark capture that the template is arriving.
Continously I get: 

Can't (yet) decode flowset id 256 from observation domain id 0, because no template to decode it with has been received. This message will usually go away after 1 minute.

Netflow is generated with IXIA packet broker.

Regards
Ana

**Comment by robcowart** [comment]
Can you share a PCAP of the flows and template? Most like there are field definitions that need to be added to the definitions file used by the decoder.

**Comment by janniten** [comment]
Hi Rob, Here a capture including a template
Thannk you
[ixflow.zip](https://github.com/logstash-plugins/logstash-codec-netflow/files/2478418/ixflow.zip)

**Comment by eijaniee** [comment]
I have the same issue. The collected flow stored into elasticsearch are not the same captured using wireshark.


![screen shot 2018-10-17 at 4 16 31 pm](https://user-images.githubusercontent.com/3070507/47073229-54533a00-d22a-11e8-9b4c-8e400931561d.png)

**Comment by robcowart** [comment]
The fix to decode IXIA IPFIX records is in commit https://github.com/logstash-plugins/logstash-codec-netflow/pull/164/commits/5f3377eb068e4431bfd6deda07b19ba7f6485de3

**Comment by eijaniee** [comment]
So we just need to upload the file (ipfix.yaml) into the correct path, replacing original file right?

**Comment by eijaniee** [comment]
I already upload the updated file but still get the same result. Netflow decode error also keep appearing on the screen non stop.

Please advice if I miss any other action.

[WARN ] 2018-10-25 18:36:34.605 [<udp.0] netflow - Can't (yet) decode flowset id 271 from observation domain id 1, because no template to decode it with has been received. This message will usually go away after 1 minute.
[WARN ] 2018-10-25 18:36:34.609 [<udp.0] netflow - Can't (yet) decode flowset id 259 from observation domain id 5, because no template to decode it with has been received. This message will usually go away after 1 minute.
[WARN ] 2018-10-25 18:36:34.609 [<udp.1] netflow - Can't (yet) decode flowset id 256 from observation domain id 0, because no template to decode it with has been received. This message will usually go away after 1 minute.

**Comment by robcowart** [comment]
Where did you "upload" it to?

The IXIA PCAP that I used did not have flowsets 259 and 271 that you are seeing. You will need to provide a PCAP.

**Comment by robcowart** [comment]
Also, please make sure you are using the `ipfix.yaml` fill from the commit...

https://github.com/logstash-plugins/logstash-codec-netflow/blob/5f3377eb068e4431bfd6deda07b19ba7f6485de3/lib/logstash/codecs/netflow/ipfix.yaml

**Comment by robcowart** [comment]
@eijaniee there are two fields in your flows that were not in the previous sample provided by @janniten. The field IDs are 192 and 193.  Do you have any IXIA documentation that describes these (and any other) fields that they might send?

**Comment by robcowart** [comment]
I figured out those two fields. Please try...
https://github.com/logstash-plugins/logstash-codec-netflow/raw/872ba39b99cde0b04b499449ab036a970b2fa727/lib/logstash/codecs/netflow/ipfix.yaml

**Comment by eijaniee** [comment]
I'm still waiting feedback on the reference from ixia guy.

Beside updating the ipfix codec file, do i need to change anything in my logstash config file? Currently here is my logstash config:



input {
  udp {
    port => 1990
    codec => netflow {
      versions => [10]
        target => ipfix
    }
    tags => "ixia"
    type => ipfix
  }
}

output {
  if "ixia" in [tags]{
      elasticsearch {
        hosts => ["x.x.x.x:9200", "x.x.x.x:9200", "x.x.x.x:9200", "x.x.x.x:9200"]
        index => "netflow-ixia-%{+YYYY.MM.dd}"
#       template => "/etc/logstash/conf.d/ixia_ipfix_template.json"
#       template_name => "my_index_template"
#        template_overwrite => true
      }
# stdout { codec => rubydebug }
  }
}

**Comment by jorritfolmer** [comment]
Closing, fixed in 4.2.0
