### ISSUE TITLE
Support for ESXi VDS - ESXi 5.1+

### ISSUE THREAD

**Issue by benlavender** [logstash-plugins/logstash-codec-netflow#28]
Ticket request to support IPFIX for ESXi 5.1 and above. Any NetFlow exports sent from ESXi devices on ESXi 5.1+ now only support IPFIX.

I have this implemented myself using this plugin including the @bodgit IPFIX support and receive the below in the logstash.log file: 

:message=>"Unsupported enterprise", :enterprise=>6876, :level=>:warn}

**Comment by bodgit** [comment]
So somewhere VMware *should* document any custom fields that they send which will be a tuple of `id`, `name` and `size` for each field. I had a quick look but couldn't see a list published anywhere.

**Comment by benlavender** [comment]
Does this help? http://sourceforge.net/p/nfdump/mailman/nfdump-discuss/thread/1492FDFF-6FAE-4FA4-9D7D-787064E5FCFB@onthenet.com.au/

I've logged a support request to VMware to see if the information can be provided.

**Comment by jorritfolmer** [comment]
Can you do some packet capturing on your logstash instance so we can look at it? 
`tcpdump -i eth0 -s 0 -w /tmp/ipfix_esxi.pcap udp and port 9995`
It seems you can attach files to posts like this, or you can use something like [filebin.ca](http://filebin.ca) to upload it to.

**Comment by jorritfolmer** [comment]
I created this patch to the `ipfix.yaml` in the @bodgit ipfix branch to support the IPFIX fields exported by a vSphere 5.5 virtual distributed switch I had access to. Since these fields are undocumented, I've simply named them after their enterprise and element id's. Any word from VMware yet on this, @benlavender ?

```diff
diff --git a/lib/logstash/codecs/netflow/ipfix.yaml b/lib/logstash/codecs/netflow/ipfix.yaml
index 70f2829..51ab7c4 100644
--- a/lib/logstash/codecs/netflow/ipfix.yaml
+++ b/lib/logstash/codecs/netflow/ipfix.yaml
@@ -1202,6 +1202,37 @@
   433:
   - :uint64
   - :ignoredLayer2FrameTotalCount
+6876:
+  880:
+  - :uint8
+  - :6876_880
+  881:
+  - :uint32
+  - :6876_881
+  882:
+  - :uint32
+  - :6876_882
+  883:
+  - :string
+  - :6876_883
+  884:
+  - :string
+  - :6876_884
+  886:
+  - :uint16
+  - :6876_886
+  887:
+  - :uint16
+  - :6876_887
+  888:
+  - :uint16
+  - :6876_888
+  889:
+  - :uint8
+  - :6876_889
+  890:
+  - :uint16
+  - :6876_890
 29305:
   1:
   - :uint64
```

A sample rubydebug output from Logstash looks like this:

```ruby
{
    "@timestamp" => "2015-11-07T21:47:04.000Z",
       "netflow" => {
                         "version" => 10,
               "sourceIPv4Address" => "172.30.11.202",
          "destinationIPv4Address" => "172.30.11.110",
                 "octetDeltaCount" => 41,
                "packetDeltaCount" => 1,
           "flowStartMilliseconds" => "2015-11-07T21:46:50.000Z",
             "flowEndMilliseconds" => "2015-11-07T21:46:50.000Z",
             "sourceTransportPort" => 1433,
        "destinationTransportPort" => 38691,
                "ingressInterface" => 202,
                 "egressInterface" => 151,
                 "layer2SegmentId" => 0,
              "protocolIdentifier" => 6,
                   "flowEndReason" => 1,
                  "tcpControlBits" => 16,
                "ipClassOfService" => 0,
                      "maximumTTL" => 128,
                   "flowDirection" => 1,
                        "6876_890" => 1,
                        "6876_888" => 2,
                        "6876_889" => 0
    },
      "@version" => "1",
          "host" => "172.16.32.201"
}
```

**Comment by benlavender** [comment]
Vendor hasn’t been much use as they’re wanting to know why we think their implementation deviates from the standard RFC5101, basically I’ve not managed to speak with anyone that is aware of their own modifications to the IPFIX exports records or understands the difference. I’ve noticed private entries in the records as below:

![export](https://cloud.githubusercontent.com/assets/11093811/11033594/4f8984f8-86dc-11e5-988f-b31f370cc483.JPG)

These correspond to your updates in the ipfix.yaml.

**Comment by hkshirish** [comment]
Hi JorritFolmerto

Upgraded the latest logstash codec from the
https://github.com/logstash-plugins/logstash-codec-netflow/pull/10
and then applied the patch for vmware ipfix.
https://github.com/logstash-plugins/logstash-codec-netflow/issues/28

Then I played the IPFix packets from VMware. Attached the same.(to your email id)

But I see following messages for the attached pcap. 
Let us know if there is any fix available for parsing the VMWare IPfix packets


********************
No matching template for flow id 257 {:level=>:warn}
No matching template for flow id 256 {:level=>:warn}
Unsupported enterprise field {:type=>950, :enterprise=>6876, :length=>4, :level=>:warn}
No matching template for flow id 256 {:level=>:warn}
Unsupported enterprise field {:type=>950, :enterprise=>6876, :length=>4, :level=>:warn}
No matching template for flow id 256 {:level=>:warn}
No matching template for flow id 256 {:level=>:warn}
No matching template for flow id 256 {:level=>:warn}
No matching template for flow id 256 {:level=>:warn}
No matching template for flow id 256 {:level=>:warn}
No matching template for flow id 256 {:level=>:warn}
No matching template for flow id 256 {:level=>:warn}
********************

**Comment by jorritfolmer** [comment]
Thanks for sending the .pcap. However there are no template packets, only data packets. Without template packets the data packets cannot be decoded, so I can't replay them to my local Logstash to test with.

Could you try capturing them too? I assume than making a capture of several minutes will include both data and template packets.

**Comment by hkshirish** [comment]
Attached the pcap which has templates.

The following packets have template in it packet 1, 135,195

Regards,
Shirish

**Comment by jorritfolmer** [comment]
I haven't found any documentation about there fields, especially the 951 field, and don't have time to look into it.
So the quickest way to get NSX data in ES is to skip these unknown fields.
If you have already modified the ipfix.yaml with the vSphere additions earlier in this thread, then add:

```
  950:
  - skip
  951:
  - skip
  952:
  - skip
```

Otherwise add:

```
6876:
  950:
  - skip
  951:
  - skip
  952:
  - skip
```

**Comment by schif1** [comment]
Hello,

Some news about the support of vDS 6.0 netflow 10 ( IPFIX) ?
Do you want some sample ?
How can i help to improve the support of VMware ?

Thanks

**Comment by jorritfolmer** [comment]
If you can send me a .pcap of vDS netflow traffic I can take a look at it. Email in profile. It would be especially helpful if you have any information about the vendor specific fields.

**Comment by zoubazouba** [comment]
Hi,

I am receiving netflow v 9 data from cisco devices. Logstash couldnt decode the netflow data and showing this output: How can I solve this problem please ?

_**{:timestamp=>"2016-08-19T10:26:17.043000+0200", :message=>"No matching template for flow id 313", :level=>:warn}
{:timestamp=>"2016-08-19T10:26:17.043000+0200", :message=>"No matching template for flow id 324", :level=>:warn}
{:timestamp=>"2016-08-19T10:26:17.052000+0200", :message=>"No matching template for flow id 324", :level=>:warn}
{:timestamp=>"2016-08-19T10:26:17.074000+0200", :message=>"No matching template for flow id 324", :level=>:warn}
{:timestamp=>"2016-08-19T10:26:17.128000+0200", :message=>"No matching template for flow id 324", :level=>:warn}
{:timestamp=>"2016-08-19T10:26:17.191000+0200", :message=>"No matching template for flow id 324", :level=>:warn}
{:timestamp=>"2016-08-19T10:26:17.222000+0200", :message=>"Pipeline main started"}
{:timestamp=>"2016-08-19T10:26:17.855000+0200", :message=>"No matching template for flow id 324", :level=>:warn}
{:timestamp=>"2016-08-19T10:26:17.879000+0200", :message=>"No matching template for flow id 324", :level=>:warn}
{:timestamp=>"2016-08-19T10:26:17.987000+0200", :message=>"No matching template for flow id 313", :level=>:warn}**_

**Comment by jorritfolmer** [comment]
Please create a separate issue since this doesn't seem to address anything VMware specific. I'll delete these comments afterwards.

**Comment by jorritfolmer** [comment]
Thanks for sending me a .pcap. It seems there is no difference between a vDS 5.5 and vDS 6.0, as far as Netflow/IPFIX is concerned.

This means you can apply the patch (see thread above) to ipfix.yaml in your Logstash install.

If you have a VMware support contract, you might want to inquire about the meaning of the 883,...,889,890 fields. Much appreciated :)

Save the patch in something like /tmp/vDS_ipfix.patch and then:

```
cd /usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-3.1.2/lib/logstash/codecs/netflow
patch < /tmp/vDS_ipfix.patch
```

**Comment by hail100** [comment]
I cannot get json data use ipfix.patch.
`input {
  udp {
        port => 4739
        codec => netflow {
      versions => [10]
      target => ipfix
    }
    type => ipfix
  }
}`
debug log
`
[2016-11-22T16:22:43,430][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:ip4_addr, :destinationIPv4Address]}
[2016-11-22T16:22:43,430][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint64, :octetDeltaCount]}
[2016-11-22T16:22:43,431][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint64, :packetDeltaCount]}
[2016-11-22T16:22:43,431][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint64, :flowStartMilliseconds]}
[2016-11-22T16:22:43,431][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint64, :flowEndMilliseconds]}
[2016-11-22T16:22:43,431][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint32, :ingressInterface]}
[2016-11-22T16:22:43,431][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint32, :egressInterface]}
`

**Comment by hail100** [comment]
Hi JorritFolmerto

I cannot get any data use vDS_ipfix.patch
some debug logs
``
[2016-11-22T16:22:43,415][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint16, :sourceTransportPort]}
[2016-11-22T16:22:43,415][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint16, :destinationTransportPort]}
[2016-11-22T16:22:43,415][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint32, :ingressInterface]}
[2016-11-22T16:22:43,416][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint32, :egressInterface]}
[2016-11-22T16:22:43,416][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint64, :layer2SegmentId]}
[2016-11-22T16:22:43,416][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint8, :protocolIdentifier]}
[2016-11-22T16:22:43,416][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint8, :flowEndReason]}
[2016-11-22T16:22:43,416][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint8, :tcpControlBits]}
[2016-11-22T16:22:43,416][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint8, :ipClassOfService]}
[2016-11-22T16:22:43,417][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint8, :maximumTTL]}
[2016-11-22T16:22:43,417][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint8, :flowDirection]}
[2016-11-22T16:22:43,417][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint16, :"6876_890"]}
[2016-11-22T16:22:43,417][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint16, :"6876_888"]}
[2016-11-22T16:22:43,417][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint8, :"6876_889"]}
[2016-11-22T16:22:43,418][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:skip, nil, {:length=>1}]}
[2016-11-22T16:22:43,422][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:ip4_addr, :sourceIPv4Address]}
[2016-11-22T16:22:43,422][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:ip4_addr, :destinationIPv4Address]}
[2016-11-22T16:22:43,422][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint64, :octetDeltaCount]}
[2016-11-22T16:22:43,422][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint64, :packetDeltaCount]}
[2016-11-22T16:22:43,422][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint64, :flowStartMilliseconds]}
[2016-11-22T16:22:43,423][DEBUG][logstash.codecs.netflow  ] Definition complete {:field=>[:uint64, :flowEndMilliseconds]}

**Comment by jorritfolmer** [comment]
@hail100 That is very little information to work with. What is your Logstash version, Logstash-codec-netflow version, logstash config? What other possible causes have you already eliminated?

**Comment by sliddjur** [comment]
@jorritfolmer Here are captured flows with template from vmware vsphere.

[vmware.zip](https://github.com/logstash-plugins/logstash-codec-netflow/files/670591/vmware.zip)

I'm also seeing [WARN ][logstash.codecs.netflow  ] Unsupported enterprise {:enterprise=>6876} in my log 

I also made a netflow_definitions file for the flows. But I don't know if they're correct?


```
---
1:
- 8
- :in_bytes
2:
- 8
- :in_pkts
4:
- :uint8
- :protocol
5:
- :uint8
- :src_tos
6:
- :uint8
- :tcp_flags
7:
- :uint16
- :l4_src_port
8:
- :ip4_addr
- :ipv4_src_addr
10:
- 4
- :input_snmp
11:
- :uint16
- :l4_dst_port
12:
- :ip4_addr
- :ipv4_dst_addr
14:
- 4
- :output_snmp
27:
- :ip6_addr
- :ipv6_src_addr
28:
- :ip6_addr
- :ipv6_dst_addr
53:
- :uint8
- :max_ttl
61:
- :uint8
- :direction
136:
- :uint8
- :flow_end_reason
152:
- 8
- :flow_start_msec
153:
- 8
- :flow_start_msec
210:
- :uint8
- :padding_octets
351:
- 8
- :layer2_segment_id

```

**Comment by jorritfolmer** [comment]
Closing this issue.
With the most recent commits support for these fields has been added, although they are marked as `vmwareUnknown880` etc.

If someone obtains the proper field definitions from VMware, feel free to create a new issue or PR.

**Comment by jimmypw** [comment]
@jorritfolmer I have done the legwork and figured out what these id's are. Here is my logstash configuration.

```
filter {
  mutate {
    # remame 6876_890 to ingress interface
    id => "vmware_890"
    rename => { "[ipfix][6876_890]" => "[ipfix][vmwareIngressInterfaceTypeID]" }
  }
  translate {
    # Give it a friendly name.
    # Note: Even if two hosts communicate on the same dv port group the packet
    # will appear to come from the Uplink Port group if they are on different
    # hosts. Rendering this data pretty much useless.
    id => "vmware_890_friendly"
    field => "[ipfix][vmwareIngressInterfaceTypeID]"
    destination => "[ipfix][ingressInterfaceTypeFriendly]"
    dictionary => [
                    "1", "UplinkPG",
                    "2", "DVPG"
                  ]
    fallback => "Unknown"
  }
}

filter {
  mutate {
    # remame 6876_888 to egress interface
    id => "vmware_888"
    rename => { "[ipfix][6876_888]" => "[ipfix][vmwareEgressInterfaceTypeID]" }
  }
  translate {
    # Give it a friendly name.
    # Note: Even if two hosts communicate on the same dv port group the packet
    # will appear to come from the Uplink Port group if they are on different
    # hosts. Rendering this data pretty much useless.
    id => "vmware_888_friendly"
    field => "[ipfix][vmwareEgressInterfaceTypeID]"
    destination => "[ipfix][egressInterfaceTypeFriendly]"
    dictionary => [
                    "1", "UplinkPG",
                    "2", "DVPG"
                  ]
    fallback => "Unknown"
  }
}

filter {
  mutate {
    # remame 6876_889 to observation domain id
    id => "vmware_889"
    rename => { "[ipfix][6876_889]" => "[ipfix][vmwareObservationDomainID]" }
  }
}
```

**Comment by jorritfolmer** [comment]
@jimmypw Thanks!
