### ISSUE TITLE
Type 56 name symbol mistake?

### ISSUE THREAD

**Issue by romale** [logstash-plugins/logstash-codec-netflow#32]
Hi, i think here is mistake:
need change
56:
- :mac_addr
- :in_src_max

to

56:
- :mac_addr
- :in_src_mac

because of:
![screen81](https://cloud.githubusercontent.com/assets/928628/12453465/606ec4b2-bfa4-11e5-9fcf-907e3b7c09b4.png)

**Comment by jorritfolmer** [comment]
Yes this is fixed whenever PR #23 is merged.
