### ISSUE TITLE
Netflow Codec v9 sampling interval

### ISSUE THREAD

**Issue by killafunkinmofo** [logstash-plugins/logstash-codec-netflow#33]
Hello,

I have been starting to try the netflow codec with v9 in place of v5. I have noticed that in my flow data sampling interval doesn't show up on a regular basis. My SRX seems to send that info periodically, but not regularly. In my configurations, I have a ruby line that multiplies the bytes and packets value with the interval. This helps gives the data actual values and help to work out per second values when analyzing the data.

When debugging logstash I can bits like this that show up occasionally:
flow_seq_num\"=>517222, \"flowset_id\"=>256, \"sampling_algorithm\"=>2, \"sampling_interval\"=>100}, \"@version\"=>\"1\", \"host\"=>\"SRX-Home\"

Is there a way to access the sampling interval in logstash config? Could the codec possible multiple bytes and packets value by the interval? Or is this something with how my SRX sends netflowV9 data?

I usually use a line like this in my netflow v5 logstash configs, which doesn't work for me in netflow9.
code => "event['netflow']['in_bytes'] = event['netflow']['in_bytes'] \* event['netflow']['sampling_interval']"

Here are al of the netflow fields that get sent to elasticsearch:
        "netflow" => {
                    "version" => 9,
               "flow_seq_num" => 538881,
                 "flowset_id" => 257,
              "ipv4_src_addr" => "162.213.157.82",
              "ipv4_dst_addr" => "69.172.168.238",
                    "src_tos" => 96,
                   "protocol" => 17,
                "l4_src_port" => 5080,
                "l4_dst_port" => 31112,
                  "icmp_type" => 0,
                 "input_snmp" => 502,
                   "src_mask" => 32,
                   "dst_mask" => 32,
                     "src_as" => "0",
                     "dst_as" => "0",
          "bgp_ipv4_next_hop" => "0.0.0.0",
                  "tcp_flags" => 0,
                "output_snmp" => 0,
              "ipv4_next_hop" => "0.0.0.0",
                   "in_bytes" => 2471,
                    "in_pkts" => 4,
             "first_switched" => "2016-01-24T19:59:14.999Z",
              "last_switched" => "2016-01-25T04:07:59.999Z",
        "ip_protocol_version" => 4
    },
        "@version" => "1",
            "host" => "SRX-Home",

**Comment by jorritfolmer** [comment]
First I guess the sampling interval is accessible through `event['sampling_interval']`.
However, it is not present at the same time as `event['netflow']['in_bytes']`, so I think you may need to use the `memorize` plugin to get the fields from different events together.

**Comment by killafunkinmofo** [comment]
That's an interesting suggestion, I haven't actually tried that plugin before. I will need to re setup on a sandbox and try sometime later though. I have shutdown this test, but this is a good reason to start it up again.

Thanks!
