### ISSUE TITLE
#<ArgumentError: wrong number of arguments (1 for 0)>

### ISSUE THREAD

**Issue by Rojuinex** [logstash-plugins/logstash-codec-netflow#34]
Howdy, I'm getting an error trying to get netflow v9 data to be parsed correctly.  It spewes the "unsupported field" and "no matching template" errors and every so often I get this error (which I think is happening when the template file is received)

```
:message => "Exception in inputworker",
"exception" => #<ArgumentError: wrong number of arguments (1 for 0)>,
"backtrace" => [
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-2.0.2/lib/logstash/codecs/netflow/util.rb:50:in `get'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.1.0/lib/bindata/array.rb:208:in `each'",
	"org/jruby/RubyArray.java:1613:in `each'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.1.0/lib/bindata/array.rb:208:in `each'",
	"org/jruby/RubyEnumerable.java:752:in `collect'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-2.0.2/lib/logstash/codecs/netflow/util.rb:50:in `get'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.1.0/lib/bindata/primitive.rb:111:in `sensible_default'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.1.0/lib/bindata/base_primitive.rb:142:in `_value'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.1.0/lib/bindata/primitive.rb:103:in `do_num_bytes'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.1.0/lib/bindata/struct.rb:250:in `sum_num_bytes_below_index'",
	"org/jruby/RubyRange.java:479:in `each'",
	"org/jruby/RubyEnumerable.java:852:in `inject'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.1.0/lib/bindata/struct.rb:247:in `sum_num_bytes_below_index'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.1.0/lib/bindata/struct.rb:243:in `sum_num_bytes_for_all_fields'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.1.0/lib/bindata/struct.rb:141:in `do_num_bytes'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.1.0/lib/bindata/base.rb:174:in `num_bytes'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-2.0.2/lib/logstash/codecs/netflow.rb:186:in `decode_netflow9'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-2.0.2/lib/logstash/codecs/netflow.rb:86:in `decode'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.1.0/lib/bindata/array.rb:208:in `each'",
	"org/jruby/RubyArray.java:1613:in `each'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.1.0/lib/bindata/array.rb:208:in `each'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-2.0.2/lib/logstash/codecs/netflow.rb:85:in `decode'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.3/lib/logstash/inputs/udp.rb:96:in `inputworker'",
	"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.3/lib/logstash/inputs/udp.rb:73:in `udp_listener'"],
	:level => :error}
```

The router is a MikroTik and has the following traffic flow settings:
```
> /ip traffic-flow print       
                enabled: yes
             interfaces: WAN
          cache-entries: 64k
    active-flow-timeout: 30m
  inactive-flow-timeout: 15s
> /ip traffic-flow target print
Flags: X - disabled 
 #   SRC-ADDRESS                                               DST-ADDRESS                                               PORT VERSION
 0   0.0.0.0                                                   10.100.0.20                                               2055 9
```

The ELK stack is running in docker from this repo: https://github.com/deviantony/docker-elk

The version of logstash that my container is currently running is: 2.1.1
And the version of netflow that it's running is: 2.0.2

Any help is much appreciated.

**Comment by echobnet** [comment]
+1 I too am having this issue with a very similar setup.

**Comment by jorritfolmer** [comment]
This seems like a duplicate of Issue #19, that has been fixed in Pull Request #23, but which hasn't been merged into master yet. However, you can apply the changes from the pull request manually to see if this fixed things.

**Comment by Rojuinex** [comment]
I applied the changes from that patch and it seems to work better, however it only imports data every minute, in between minutes I still get the "Unsupported field" and "No matching template" errors.  Any suggestions?

![screen shot 2016-02-20 at 5 06 11 am](https://cloud.githubusercontent.com/assets/2524890/13196616/e86b4b6c-d78f-11e5-922b-f1c3bca954de.png)

**Comment by jorritfolmer** [comment]
It's probably better to look at a rubydebug output from logstash to determine if you're happy with the data it is collecting. 

As for the "no matching template" errors, you may hit issue #9. How many netflow devices are you exporting to logstash?

As for the "unsupported field", does it give any more info than this to go on?

**Comment by Rojuinex** [comment]
I'll take a look at the output as well as at issue #9.  At the moment I'm only exporting from 1 device.

These are the errors I get.

I think the unsupported is related to [#12](https://github.com/logstash-plugins/logstash-codec-netflow/issues/12)

logstash_1 | {:timestamp=>"2016-02-22T17:12:33.483000+0000", :message=>"Unsupported field", :type=>225, :length=>4, :level=>:warn}
logstash_1 | {:timestamp=>"2016-02-22T17:12:33.484000+0000", :message=>"No matching template for flow id 256", :level=>:warn}

Heres a pastebin of full output until I get actual records output http://pastebin.com/NZkA0He6

**Comment by jorritfolmer** [comment]
Ah great, you could try to edit `netflow.yaml` and add to get rid of the missing field message, and hopefully the other as well:

```
225:
- :ip4_addr
- :postNATSourceIPv4Address
```

**Comment by Rojuinex** [comment]
Adding that field helped.  I got some more errors but I followed the info on [this page](http://www.cisco.com/c/en/us/td/docs/security/asa/special/netflow/guide/asa_netflow.html) to add
```
216 225:
- :ip4_addr
- :postNATSourceIPv4Address
226:
- :ip4_addr
- :postNATDestinationIPv4Address
227:
- 2
- :postNATTSourceTransportPort
228:
- 2
- :postNATTDestinationTransportPort
```

And now I only get a few "No matching template" errors upon startup and sometimes I get a "Template length doesn't fit cleanly into flowset" Aside from that everything seems to be working excellently!  Thanks for the awesome plugin!

In case you're curious to the template error:
```
logstash_1 | {:timestamp=>"2016-02-23T17:22:51.019000+0000", :message=>"Template length doesn't fit cleanly into flowset", :template_id=>257, :template_length=>101, :record_length=>1428, :level=>:warn}
```
