### ISSUE TITLE
how to send netflow to logstash and elasticsearch

### ISSUE THREAD

**Issue by kan1207** [logstash-plugins/logstash-codec-netflow#35]
I have been browsing for different sites on how to send network traffic data to logstash and elasticsearch; nevertheless, could not find an effective way to do so.

Wonder could anyone give me some steps and guidelines

Great thanks

**Comment by jorritfolmer** [comment]
This minimal config for Logstash should work:

```
input {
    udp {
      port => 2055
      codec => netflow
    }
}

output {
  elasticsearch { hosts => ["localhost:9200"] }
}
```

**Comment by kan1207** [comment]
It seems unable to fetch mapping. Any add-ons need to be configured?

**Comment by jorritfolmer** [comment]
Ah apologies, the config above is for Logstash 2.x so you're probably running Logstash 1.x.
If so, this config may yield better results. At the very least you should see Logstash listening to port 2055 with this:

```
input {
  udp {
    port => 2055
    codec => netflow
  }
}

output {
  elasticsearch {
    protocol => "http"
    host => "127.0.0.1"
  }
}
```

**Comment by jorritfolmer** [comment]
It looks like the documentation will get an update soon, see #56.

**Comment by jorritfolmer** [comment]
Docs have been updated. See [here](https://www.elastic.co/guide/en/logstash/current/plugins-codecs-netflow.html)
