### ISSUE TITLE
Number Format Exception when parsing mac address

### ISSUE THREAD

**Issue by rudolphosu** [logstash-plugins/logstash-codec-netflow#40]
Hi, I am receiving the following error when trying to index netflow records: 

"error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [netflow.staMacAddress]", "caused_by"=>{"type"=>"number_format_exception", "reason"=>"For input string: \"2c:33:7a:5b:46:bb\""}}}}, :level=>:warn}

This is after applying the change to util.rb from PR #23 
My terminal output shows that the mac address appears to be parsed cleanly:

"staMacAddress" => "2c:33:7a:5b:46:bb",

So I am unsure why they aren't making it into elasticsearch.  Any insight would be greatly appreciated

**Comment by jorritfolmer** [comment]
This looks like an Elasticsearch error, not a Logstash one, or one related to the logstash-codec-netflow. Perhaps you could check the elasticsearch logging for clues. Most likely you'll need to tell Elasticsearch that staMacAddress is now of type string, instead of whatever is previously was.

**Comment by rudolphosu** [comment]
issue resolved, thanks
