### ISSUE TITLE
Cannot install 3.1.2 with Logstash 2.3.4

### ISSUE THREAD

**Issue by cvicente** [logstash-plugins/logstash-codec-netflow#42]
Hi,

I am interested in using this plugin with IPFIX support, so I need the latest version. However I cannot install it. This is Ubuntu 14.04. Logstash installed using latest deb package:

```
$ bin/logstash --version
logstash 2.3.4
```

I tried to update the plugin using the following:
```
$ sudo /opt/logstash/bin/logstash-plugin update logstash-codec-netflow
You are updating logstash-codec-netflow to a new version 3.1.2, which may not be compatible with 2.1.1. are you sure you want to proceed (Y/N)?
Y
Updating logstash-codec-netflow

No plugin updated
```

I then downloaded the latest gem from rubygems, and tried:

```
$ sudo bin/logstash-plugin install ~/logstash-codec-netflow-3.1.2.gem
Validating /home/cvicente/logstash-codec-netflow-3.1.2.gem
Installing logstash-codec-netflow
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core-plugin-api":
  In snapshot (Gemfile.lock):
    logstash-core-plugin-api (= 1.20.0)

  In Gemfile:
    logstash-codec-multiline (>= 0) java depends on
      logstash-core-plugin-api (~> 1.0) java
```

The 3.1.2 Changelog mentions:

```
Relax constraint on logstash-core-plugin-api to >= 1.60 <= 2.99
```

Which seems to suggest that the plugin is no longer compatible with logstash 2.3.4. Does that mean I have to run logstash Alpha? I didn't want to run alpha code, really.

Thanks in advance

**Comment by jorritfolmer** [comment]
Yes the 3.x version of this codec is for Logstash 5.x, which isn't out of beta yet.
The most recent 2.x version does work for Logstash 2.x, so you should try to do something like this:

```
/opt/logstash/bin/logstash-plugin uninstall logstash-codec-netflow
```

and then:

```
/opt/logstash/bin/logstash-plugin install --version 2.1.1 logstash-codec-netflow
```

**Comment by cvicente** [comment]
Thanks, but I can't use 2.1.1 because I need IPFIX support, and it came in 3.1.0. 

It's unfortunate the the plugin can't be made backwards compatible with previous core API versions.

**Comment by jorritfolmer** [comment]
2.1.1 includes IPFIX support, see https://github.com/logstash-plugins/logstash-codec-netflow/blob/v2.1.1/CHANGELOG.md

**Comment by cvicente** [comment]
Oh, I see. I was going by the Changelog in the master branch: 
https://github.com/logstash-plugins/logstash-codec-netflow/blob/master/CHANGELOG.md

Thanks!
