### ISSUE TITLE
Documentation issue: Unknown setting 'definitions' for netflow

### ISSUE THREAD

**Issue by ClaudioRifo** [logstash-plugins/logstash-codec-netflow#56]
Please update documentation regarding the use of custom definitions.

Change:
          definitions
to:
          netflow_definitions

**Comment by jorritfolmer** [comment]
Documentation is supposed to be automatically generated from the sourcecode.
However, this needs to be run manually. I'll ping the devs upstream.

**Comment by jordansissel** [comment]
There's a problem with the tooling we use for publishing documentation. We're working on it.

**Comment by jorritfolmer** [comment]
Docs have been updated. See [here](https://www.elastic.co/guide/en/logstash/current/plugins-codecs-netflow.html)
