### ISSUE TITLE
Cannot read flow templates from cache file

### ISSUE THREAD

**Issue by ajrgrubbs** [logstash-plugins/logstash-codec-netflow#68]
Logstash is unable to start with this plugin if `cache_save_path` is provided to the codec, and a valid cache file exists at that path.

- Version:
    - logstash-codec-netflow: v3.2.2
    - logstash: v5.2.0
- Operating System: Ubuntu 14.04.5
- Config File (if you have sensitive info, please remove it):
```
input {
  udp {
    type => "netflow"
    port => "5045"
    codec => netflow {
      versions => [5, 9, 10]
      cache_save_path => "/etc/logstash"
    }
  }
}
```

- Sample Data: You'll need a valid netflow template cache. I am unable to provide my own, unfortunately.
- Steps to Reproduce:
1. Set up your logstash input with a configuration that specifies a directory with `cache_save_path`
1. Either provide a valid cache file (named `netflow_templates.cache`) in the directory specified above, or use actual netflow data to create the cache for you.
1. Start logstash. It will say the template cache is "corrupt".

**Comment by ajrgrubbs** [comment]
So it appears this is only due to a missing `require "json"` at the top of netflow.rb. I'm setting up a proper dev environment for this plugin, will verify and submit a proper pull request with the fix soonish.

**Comment by gjmoed** [comment]
Hey guys, so I created that caching feature and now I'm a bit puzzled by your findings. Very possible something changed with newer logstash versions of course but if I recall correctly, one should always use the logstash/json in favor of the plain json. Should not need both, at least, that hasn't been the case before. So obviously this was posing a problem but now that you did setup a dev env to work on this and submit a PR, I'm just curious what your experiences are/were with the relevant tests for the caching feature? In any event, just for the record :-) I did play around with both plain json and logstash/json, in the end logstash/json was recommended and at the time seemed to work just fine. I'm sorry if somehow this caused or is causing issues nonetheless. Cheers! GJ

**Comment by ajrgrubbs** [comment]
The tests actually were already using `require "json"` themselves for de/serialization. Not surprising that if something changed in logstash/json to prevent this from working anymore, the tests didn't catch it.

**Comment by gjmoed** [comment]
ah! Excellent observation, tnx for that. Next chance I get I'll test both ways and see what happens. As mentioned, it feels awkward having to require both logstash/json as well as plain json. Just maybe this is a simple jruby vs mri challenge ;-)
