### ISSUE TITLE
Netflow v9/ipfix: No matching template for flow id 257/258

### ISSUE THREAD

**Issue by fi-ro** [logstash-plugins/logstash-codec-netflow#72]
Hi, 
I am running into issues when importing flows via logstash into elasticsearch.
The messages are:

```[WARN ][logstash.codecs.netflow  ] Unsupported field in template 257 {:type=>57590, :length=>2} 
[WARN ][logstash.codecs.netflow  ] Unsupported field in template 258 {:type=>57590, :length=>2}
[WARN ][logstash.codecs.netflow  ] No matching template for flow id 257
[WARN ][logstash.codecs.netflow  ] No matching template for flow id 258
[WARN ][logstash.codecs.netflow  ] Invalid netflow packet received (value '0' not as expected for obj.records[1].flowset_length)
[WARN ][logstash.codecs.netflow  ] Invalid netflow packet received (value '0' not as expected for obj.records[1].flowset_length)
```
My logstash config is:
```
input {
        udp {
                host => localhost
                port => 15000
                codec => netflow {
                        versions => [9,10]
                        target => netflow
                }
                type => netflow
        }
}
filter {}
output {
        stdout {
                codec => "json"
        }
       elasticsearch {
               hosts => ["localhost:9200"]
       }
}
```

In the web I found similar issues for other flow id, but no applicable solution.
The flow are coming from an [cento ](http://www.ntop.org/products/netflow/nprobe-cento/ )instance. The issues are the same running netflow v9 or ipfix.
Is there a way to add the missing templates?

Also am I not seeing any data arriving in elasticsearch. I'm guessing this has to do with the issues with the templates?

I'm running:
ubuntu 16.04 4.4.0-64-generic
logstash 5.2.2-1
elasticsearch 5.2.2
cento v.1.3.170228

If you need more information I'm happy to provide more logs etc.

Cheers

**Comment by jorritfolmer** [comment]
Can you send a pcap? 60 seconds of Netflow traffic will do usually.

**Comment by fi-ro** [comment]
I'll try to prepare a pcap file for you. I have to anonymize the flows and am currently looking for tools to do that.

**Comment by sliddjur** [comment]
@fi-ro https://wiki.wireshark.org/Tools#Capture_file_anonymization I used tracewrangler with great success

**Comment by fi-ro** [comment]
sliddjur: thanks, but tracewrangler sig-faulted on my machine...that was more complicated than I thought.
@jorritfolmer: do you have an email where I can send you the pcap (~30MB)?

**Comment by jorritfolmer** [comment]
Yeah should be no problem, email in profile.

**Comment by jorritfolmer** [comment]
Any update on this?
