### ISSUE TITLE
IP addresses appear as "string fields"

### ISSUE THREAD

**Issue by borjam** [logstash-plugins/logstash-codec-netflow#74]
It's either a bug or something is missing in the documentation. 

Running Elasticsearch 5.2.2, Logstash 5.2.2, Kibana 5.2.2.

Logstash config:
input {
        udp {
                host => "192.168.1.202"
                port => 2072
                codec => netflow {
                        versions => [5]
                        target => netflow
                        cache_save_path => "/tmp"
                }
        }
}

Trying with either versions 5, 9 or 10, IP addresses get "string" type rather than "ip". I'm rather lost, new to ELK. Netflow is exported from a Mikrotik router running version 6.39rc25. Anyway it shouldn't be an issue. And Netflow works, I am sending in parallel to a nfsen and it works perfectly.

GET /logstash-2017.03.17/_mappings

{
  "logstash-2017.03.17": {
    "mappings": {
      "netflow": {
        "_all": {
          "enabled": true,
          "norms": false
        },
        "dynamic_templates": [
          {
            "message_field": {
              "path_match": "message",
              "match_mapping_type": "string",
              "mapping": {
                "norms": false,
                "type": "text"
              }
            }
          },
          {
            "string_fields": {
              "match": "*",
              "match_mapping_type": "string",
              "mapping": {
                "fields": {
                  "keyword": {
                    "type": "keyword"
                  }
                },
                "norms": false,
                "type": "text"
              }
            }
          }
        ],
        "properties": {
          "@timestamp": {
            "type": "date",
            "include_in_all": false
          },
          "@version": {
            "type": "keyword",
            "include_in_all": false
          },
          "geoip": {
            "dynamic": "true",
            "properties": {
              "ip": {
                "type": "ip"
              },
              "latitude": {
                "type": "half_float"
              },
              "location": {
                "type": "geo_point"
              },
              "longitude": {
                "type": "half_float"
              }
            }
          },
          "host": {
            "type": "text",
            "norms": false,
            "fields": {
              "keyword": {
                "type": "keyword"
              }
            }
          },
          "netflow": {
            "properties": {
              "dst_as": {
                "type": "long"
              },
              "dst_mask": {
                "type": "long"
              },
              "engine_id": {
                "type": "long"
              },
              "engine_type": {
                "type": "long"
              },
              "first_switched": {
                "type": "date"
              },
              "flow_records": {
                "type": "long"
              },
              "flow_seq_num": {
                "type": "long"
              },
              "in_bytes": {
                "type": "long"
              },
              "in_pkts": {
                "type": "long"
              },
              "input_snmp": {
                "type": "long"
              },
              "ipv4_dst_addr": {
                "type": "text",
                "norms": false,
                "fields": {
                  "keyword": {
                    "type": "keyword"
                  }
                }
              },
              "ipv4_next_hop": {
                "type": "text",
                "norms": false,
                "fields": {
                  "keyword": {
                    "type": "keyword"
                  }
                }
              },
              "ipv4_src_addr": {
                "type": "text",
                "norms": false,
                "fields": {
                  "keyword": {
                    "type": "keyword"
                  }
                }
              },
              "l4_dst_port": {
                "type": "long"
              },
              "l4_src_port": {
                "type": "long"
              },
              "last_switched": {
                "type": "date"
              },
              "output_snmp": {
                "type": "long"
              },
              "protocol": {
                "type": "long"
              },
              "sampling_algorithm": {
                "type": "long"
              },
              "sampling_interval": {
                "type": "long"
              },
              "src_as": {
                "type": "long"
              },
              "src_mask": {
                "type": "long"
              },
              "src_tos": {
                "type": "long"
              },
              "tcp_flags": {
                "type": "long"
              },
              "version": {
                "type": "long"
              }
            }
          },
          "type": {
            "type": "text",
            "norms": false,
            "fields": {
              "keyword": {
                "type": "keyword"
              }
            }
          }
        }
      },
      "_default_": {
        "_all": {
          "enabled": true,
          "norms": false
        },
        "dynamic_templates": [
          {
            "message_field": {
              "path_match": "message",
              "match_mapping_type": "string",
              "mapping": {
                "norms": false,
                "type": "text"
              }
            }
          },
          {
            "string_fields": {
              "match": "*",
              "match_mapping_type": "string",
              "mapping": {
                "fields": {
                  "keyword": {
                    "type": "keyword"
                  }
                },
                "norms": false,
                "type": "text"
              }
            }
          }
        ],
        "properties": {
          "@timestamp": {
            "type": "date",
            "include_in_all": false
          },
          "@version": {
            "type": "keyword",
            "include_in_all": false
          },
          "geoip": {
            "dynamic": "true",
            "properties": {
              "ip": {
                "type": "ip"
              },
              "latitude": {
                "type": "half_float"
              },
              "location": {
                "type": "geo_point"
              },
              "longitude": {
                "type": "half_float"
              }
            }
          }
        }
      }
    }
  }
}

**Comment by jorritfolmer** [comment]
This looks more like an Elasticsearch issue to me. I believe you should tell Elasticsearch to map these fields to ip type. Logstash doesn't have any role in this, it just supplies keys and values to ES.
