### ISSUE TITLE
Netflow v5 is not parsed correctly

### ISSUE THREAD

**Issue by michalterbert** [logstash-plugins/logstash-codec-netflow#77]
Hi!

I'm still using logstash 2.4.1 (with logstash-codec-netflow (2.1.1)) where events are correctly parsed:
```java
"netflow"  => {
 "version" => 5,
 "flow_seq_num" => 192649620,
 "engine_type" => 0,
 "engine_id" => 7,
 "sampling_algorithm" => 0,
 "sampling_interval" => 0,
 "flow_records" => 30,
 "ipv4_src_addr" => "10.10.10.10",
 "ipv4_dst_addr" => "10.20.20.20",
 "ipv4_next_hop" => "0.0.0.0", 
 "input_snmp" => 11,
 "output_snmp" => 0,
 "in_pkts" => 1,
 "in_bytes" => 74,
 "first_switched" => "2017-06-07T06:34:35.382Z",
 "last_switched" => "2017-06-07T06:34:35.382Z",
 "l4_src_port" => 59176,
 "l4_dst_port" => 53,
 "tcp_flags" => 0,
 "protocol" => 17,
 "src_tos" => 0,
 "src_as" => 0, 
 "dst_as" => 0,
 "src_mask" => 0,
 "dst_mask" => 0
}
```

But when I try to use the latest logstash 5.4.1 with logstash-codec-netflow 3.4.0, I have wrong parsed events, like this below:
```java
"netflow" => {
 "version" => 5,
 "flow_seq_num" => 3186606013,
 "engine_type" => 22,
 "engine_id" => 95,
 "sampling_algorithm" => 3,
 "sampling_interval" => 12223,
 "flow_records" => 30,
 "ipv4_src_addr" => "0.0.10.239",
 "ipv4_dst_addr" => "191.189.10.239",
 "ipv4_next_hop" => "191.189.10.239",
 "input_snmp" => 49085,
 "output_snmp" => 61375,
 "in_pkts" => 3171418112,
 "in_bytes" => 9,
 "first_switched" => "2070-12-04T08:40:46.496Z",
 "last_switched" => "2070-12-04T08:41:52.496Z",
 "l4_src_port" => 40,
 "l4_dst_port" => 25908,
 "tcp_flags" => 73,
 "protocol" => 101,
 "src_tos" => 52,
 "src_as" => 27209,
 "dst_as" => 61375,
 "src_mask" => 189,
 "dst_mask" => 239,
}
```

As You can see I have issue with IP Address, timestamp fields - first_switched, last_switched and other :(

Configuration for both logstash is very simple:
- input Kafka (2.4.1 - from ZK, 5.4.1 from Kafka Brokers)
- no filter
- output Stdin

Do you have any ideas how to resolved this issue?

**Comment by jorritfolmer** [comment]
Both times exactly the same device you're exporting Netflow from? This sort of thing should ortherwise have been caught by our rspec tests, we test against multiple netflow v5 samples.

Could you mail me a pcap with the netflow traffic so I can take a look whats going on?

**Comment by michalterbert** [comment]
Yes both times was exactly the same device. How to prepare pcap for you?

**Comment by jorritfolmer** [comment]
On your logstash instance, leave this running for a couple of minutes.
Modify the interface and port to match your own environment:

`tcpdump -i eth0 -s 0 -w /tmp/netflow_issue_77.pcap udp and port 9995`

**Comment by jorritfolmer** [comment]
Did you manage to prepare the pcap?
