### ISSUE TITLE
No matching template for flow id 261

### ISSUE THREAD

**Issue by Devorkin** [logstash-plugins/logstash-codec-netflow#78]
- Version: Logstash 5.4.1/logstash-codec-netflow (3.4.0)
- Operating System: CentOS Linux release 7.3.1611
- Device which gathering Netflow data from: Cisco WLC 2504
- Device software version: 8.2.111.0
- Device Netflow version: 9
 
- Config 
```
input {
        udp {
                port    =>      9995
                codec   =>    netflow
                type    =>      netflow
                tags    =>      "netflow9"
        }
}

output {
        if "netflow9" in [tags] {
                elasticsearch {
                index   =>      "logstash_netflow9-%{+YYYY.MM.dd}"
                        hosts   =>      ["localhost:9200"]
                }
        }
}
```

- Sample Data:
```
[@TIMESTAMP][DEBUG][logstash.codecs.netflow  ] Received template 256 with fields [[:uint32, :scope_system], [:application_id, :application_id], [:string, :application_name, {:length=>64, :trim_padding=>true}]]
...
...
[@TIMESTAMP][WARN ][logstash.codecs.netflow  ] Unsupported field in template 261 {:type=>365, :length=>6}
...
...
[@TIMESTAMP][DEBUG][logstash.codecs.netflow  ] Start processing data flowset 261
[@TIMESTAMP][WARN ][logstash.codecs.netflow  ] No matching template for flow id 261
```
- Steps to Reproduce:
Start Logstash
View the logs
Receive the above warnings repeatedly

Using Wireshark with a Pcap file from TCPdump and decode as CFlow I was able to see the needed data I'm looking for (SRC\DST ips, SSID, etc...) under template 261; But Logstash cannot.

While using `codec  =>      plain  { charset => "UTF-8" }` didn't really help to see clear text of the Flow to investigate it future more.
I've got logstash log containing both `codec => plain` & `codec => netflow` output in debug, also got a Pcap if needed for troubleshoot.

I would like to know if this plugin will be able to handle this kind of Netflow data or not.
If I can help investigate or troubleshoot it, please let me know how and I will do my best!

Thanks.

**Comment by jorritfolmer** [comment]
Can you send me the .pcap so I can take a look? Email in profile.

**Comment by Devorkin** [comment]
The email has been sent.
