### ISSUE TITLE
ASR 1000 Netflow v9 template issue

### ISSUE THREAD

**Issue by brasaoud** [logstash-plugins/logstash-codec-netflow#79]
Hello

I have some issues with logstash Netflow codec and Cisco ASR 1000.
I think that logstash is not able to create templates when it receives template record packets.

I have in logs the following messages : 
[2017-06-26T12:38:56,622][WARN ][logstash.codecs.netflow  ] Unsupported field in template 275 {:type=>359, :length=>8}
[2017-06-26T12:38:56,988][WARN ][logstash.codecs.netflow  ] No matching template for flow id 275
[2017-06-26T12:38:57,316][WARN ][logstash.codecs.netflow  ] No matching template for flow id 271
[2017-06-26T12:38:57,379][WARN ][logstash.codecs.netflow  ] Unsupported field in template 277 {:type=>359, :length=>8}
.....

Thanks in advance for the help.

For all general issues, please provide the following details for fast resolution:

- Version: Codec version 3.4.0
- Operating System: Linux Ubuntu 16.04.2
- Config File (if you have sensitive info, please remove it): 
input {
  udp {
    port => 2055
    codec => netflow {
        #netflow_definitions => "/usr/share/logstash/vendor/local_gems/logstash-codec-netflow/lib/logstash/codecs/netflow/netflow.yaml"
        include_flowset_id => true
        enable_metric => true
        versions => [5, 9]
    }
    type => netflow
  }
}
- Sample Data: (Attached Files)
- Steps to Reproduce:
![netflow9_data_record](https://user-images.githubusercontent.com/12787583/27535936-1b291bfe-5a6d-11e7-85be-81c0a174cbe8.JPG)
![netflow9_template_record](https://user-images.githubusercontent.com/12787583/27535935-1b286de4-5a6d-11e7-9025-13d36d456626.JPG)

**Comment by jorritfolmer** [comment]
Can you send me a .pcap so I can fix this?

**Comment by brasaoud** [comment]
Thanks for your comment.
In the meanwhile i figure out how to solve the issue.
I had to declare all specific templates and fields size and names generated by Cisco routers.
I did it in netflow.yaml and ipfix.yaml with Pen=9.
