### ISSUE TITLE
IP address distortion with Mikrotik and IPFIX when enabling SrcNAT and DstNAT

### ISSUE THREAD

**Issue by bruberg** [logstash-plugins/logstash-codec-netflow#81]
Using a Mikrotik unit, RouterOS 6.39.2, configured with IPFIX, everything works fine with a limited number of fields being shipped. However, when activating what Mikrotik refers to as "NAT Src Address" and "NAT Dst Address", IP addresses and other fields in netflow records are randomly being heavily distorted.

I see that bug reports to Mikrotik has been mentioned previously, but I don't see what might have resulted from it, if anything. I will be happy to file a new ticket if we could find out what needs to be done.

I can provide a pcap with corresponding distorted Logstash results, but would prefer not to do so publicly. Is there a way a pcap can be submitted privately?

**Comment by jorritfolmer** [comment]
You can mail me the pcap, I'll take a look at it.
My email is in my profile.

**Comment by jorritfolmer** [comment]
Thanks for you pcap!
I'm unable to reproduce the behaviour you describe with your pcap.
My setup is similar to yours (Logstash 5.5, logstash-codec-netflow 3.5.1.

Can you try looking directly at the output from Logstash? That way we can rule out Elasticsearch/Kibana. For example with something like this in the output?

```
output {
  file { codec => "rubydebug" path => "/tmp/github_issue_81.log" }
}
```

Other ideas:

- Do you have multiple mikrotiks running with slightly different versions, that emit slightly different ipfix templates?
- Do you have template cache enabled? Perhaps the codec is decoding with a template cached from a previous routeros version?

**Comment by bruberg** [comment]
You are most likely on to something. I have two routers feeding the unit with IPFIX data, of which one had the NAT fields activated and the other had not. I activated the NAT fields on both and the problems seems to have disappeared.

After reactivating the NAT fields on one and disabling on the other, the debug file clearly showed some distorted entries, like this one:

```
       "netflow" => {
               "destinationIPv4Address" => "4.157.118.185",
             "destinationTransportPort" => 0,
                   "flowStartSysUpTime" => 2,
                       "tcpControlBits" => 255,
        "postNATDestinationIPv4Address" => "3.0.0.1",
                     "flowEndSysUpTime" => 130,
                    "sourceIPv4Address" => "255.255.255.255",
                     "ingressInterface" => 285256724,
                              "version" => 10,
                     "packetDeltaCount" => 3111325083,
                            "ipVersion" => 142,
                   "protocolIdentifier" => 255,
             "postNATSourceIPv4Address" => "20.0.0.0",
                      "egressInterface" => 84934655,
                      "octetDeltaCount" => 5,
                 "ipNextHopIPv4Address" => "20.157.118.185",
                  "sourceTransportPort" => 0
    },
```

From this I think the conclusion will be that the conflicting templates is the reason why it happens. Honestly I had no idea that the two different sources would cause such a conflict.

Thank you for pointing me in the right direction!

**Comment by robcowart** [comment]
This issue will be addressed once the following PRs are merged and released for the...

Logstash UDP Input: https://github.com/logstash-plugins/logstash-input-udp/pull/46
Logstash Netflow Codec: https://github.com/logstash-plugins/logstash-codec-netflow/pull/187
