### ISSUE TITLE
Unary vs Binary operator warning

### ISSUE THREAD

**Issue by untergeek** [logstash-plugins/logstash-codec-netflow#82]
Thankfully, it appears that Ruby is doing the Right Thing™:

```
$LS_HOME/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.5.1/lib/logstash/codecs/netflow/util.rb:208: warning: `-' after local variable or literal is interpreted as binary operator
$LS_HOME/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.5.1/lib/logstash/codecs/netflow/util.rb:208: warning: even though it seems like unary operator
```

[Line 208](https://github.com/logstash-plugins/logstash-codec-netflow/blob/v3.5.1/lib/logstash/codecs/netflow/util.rb#L208):

```
string  :padding, :read_length => lambda { flowset_length - 4 - scope_length - option_length - 2 - 2 -2}
```

To fix the warning, the proposed change is for the last `-2` to be `- 2`

**Comment by jordansissel** [comment]
https://github.com/logstash-plugins/logstash-codec-netflow/commit/59f65f87e5633c0c1239bc684bc85c7044ef1ea2


I accidentally committed this directly in Github's `edit` feature which defaults to commit instead of a PR. My bad.

**Comment by jordansissel** [comment]
Closing assuming my commit fixed it.
