### ISSUE TITLE
Missing fields, parsing errors

### ISSUE THREAD

**Issue by timmernet** [logstash-plugins/logstash-codec-netflow#87]
Followed guide from https://github.com/robcowart/elastiflow/ 

Trying to get netflow data into elasticsearch from a Cisco ASA 5515 running v9.6.2

Missing fields in Elasticseach/Kibana, for example first_switched and last_switched.
Removed logstash filter for better readability of included logfiles.

[elasticsearch.log.txt](https://github.com/logstash-plugins/logstash-codec-netflow/files/1214123/elasticsearch.log.txt)
[logstash-plain.log.txt](https://github.com/logstash-plugins/logstash-codec-netflow/files/1214124/logstash-plain.log.txt)
[netflow-asa5515.pcap.txt](https://github.com/logstash-plugins/logstash-codec-netflow/files/1214125/netflow-asa5515.pcap.txt)

Many parsing errors in elasticsearch.log

- Version: Logstash and Elasticsearch 5.5.1, logstash-codec-netflow 3.5.1
- Operating System: Ubuntu 16.04.3
- logstash config:

```
input {
    udp {
        port => 9996
        type => "netflow"
        codec => netflow { 
		    versions => [5,9] 
			cache_save_path => "/var/lib/logstash/cache"
	    }
    }
}

filter { }	

output {
    if [type] == "netflow" {
        elasticsearch {
            hosts => [ "127.0.0.1:9200" ]
            index => "netflow-%{+YYYY.MM.dd}"
            template => "/etc/logstash/templates/netflow.template.json"
            template_name => "netflow"
            template_overwrite => "true"
        }
    }
}
```

**Comment by jorritfolmer** [comment]
In your Logstash filters you should create some logic to normalize the various timestamp fields:

- first_switched
- last_switched
- event_time_msec
- flow_start_msec

Your flows contain event_time_msec and flow_start_msec instead of first_switched and last_switched

**Comment by jorritfolmer** [comment]
I wasn't able to reproduce any parse errors based on your pcap.
Also your logstash-plain.log does not contain any warning or errors.
