### ISSUE TITLE
Persist netflow template to survive a config reload

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [logstash-plugins/logstash-codec-netflow#88]
When config is reloaded (`-r` or otherwise), netflow data is missing until a template arrives again.  This is somewhat expected, however might be nice to persist the template to survive the reload.

**Comment by jorritfolmer** [comment]
The `cache_save_path` option is probably what you're looking for, see https://www.elastic.co/guide/en/logstash/current/plugins-codecs-netflow.html#plugins-codecs-netflow-cache_save_path
