### ISSUE TITLE
Netflow v9 of a particular format fails to be parsed by logstash

### ISSUE THREAD

**Issue by bluefangs** [logstash-plugins/logstash-codec-netflow#92]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

**- Version:** Logstash version is 5.6.2. netflow-codec version: 3.5.2

**- Operating System:** Ubuntu 16.04

**- Config File :** All files pertaining to logstash config is located [here](https://github.com/robcowart/elastiflow/tree/master/logstash).

**- Sample Data:** Attached a tar.gz that contains two pcap files that will be explained below.

**- Steps to Reproduce:**

1. I first installed netflow codec by running the below: 

```
App-Devp:/usr/share/logstash/bin$ sudo ./logstash-plugin install logstash-codec-netflow
Validating logstash-codec-netflow
Installing logstash-codec-netflow
Installation successful
```

2. Post this I set up the filters and other requirements as per [this repo](https://github.com/robcowart/elastiflow)

3. Logstash listens to port 2055 on my localhost.

4. Tried sending netflow information from two sources. Both the pcap files are attached.

`172.pacp` => contains netflow records generated by `pfsense` where template info is stored separately in a record while the actual data is stored in a separate record. This is parsed by logstash without any issue and is able to be viewed in kibana.

`nps.pcap` => contains netflow records generated by router where in both the template and data is stored in the same record. This never gets past logstash. I'm unable to see any sort of messages in logstash logs either. All that I can confirm that the netflow data is being correctly sent to 2055 on my device.

**Is this somehow related to the famous issue [#9?](https://github.com/logstash-plugins/logstash-codec-netflow/issues/9) - I tried both way of importing from both collectors simultaneously vs sequentially one after another. But in both cases, the content of nps.pcap never makes it, logs say nothing.**

I would like to have some insight as to why this is so. Is it something that's got to do with the format difference as mentioned above? If so, what will I need to change?

(Tagging @robcowart - as an FYI)

[pcap.tar.gz](https://github.com/logstash-plugins/logstash-codec-netflow/files/1340738/pcap.tar.gz)

**Comment by jorritfolmer** [comment]
Thanks for the pcap!
I've fixed this is the most recent commit.
This will be in v3.6.0, released later today.

**Comment by bluefangs** [comment]
Thanks for the quick turnaround @jorritfolmer . For my knowledge prospective, may I know which part of the code was changed to accommodate this?

**Comment by jorritfolmer** [comment]
This is the commit: 01b447b87a7dd00ac4f11d93f3c3ca73bad165dc

Most important parts are the additions to netflow.yaml
And the ` when :application_id` at L479 of netflow.rb

**Comment by bluefangs** [comment]
@jorritfolmer  - 

I was trying to install the latest version v3.6.0  I tried removing the current codec installation that I have (3.4.1). But when I reinstall, I still am having 3.4.1 How do I get the 3.6.0 version?

```
./logstash-plugin list --verbose | grep -i netflow
logstash-codec-netflow (3.4.1)
sudo ./logstash-plugin install logstash-codec-netflow
Validating logstash-codec-netflow
Installing logstash-codec-netflow
Installation successful
./logstash-plugin list --verbose | grep -i netflow
logstash-codec-netflow (3.4.1)
```

**Comment by bluefangs** [comment]
@jorritfolmer  - I got a chance to test this today morning and it seems to be not working. I did the below to install the latest version. I've also attached the latest pcap file that I've tested it on.
```
sudo ./logstash-plugin list --verbose | grep -i netflow
logstash-codec-netflow (3.5.2)
demo-system:/usr/share/logstash/bin$ sudo ./logstash-plugin remove logstash-codec-netflow
Successfully removed logstash-codec-netflow
demo-system:/usr/share/logstash/bin$ sudo ./logstash-plugin install --version 3.6.0 logstash-codec-netflow
Validating logstash-codec-netflow-3.6.0
Installing logstash-codec-netflow
Installation successful

demo-system:/usr/share/logstash/bin$ sudo ./logstash-plugin list --verbose | grep -i netflow
logstash-codec-netflow (3.6.0)
```

[netflow.tar.gz](https://github.com/logstash-plugins/logstash-codec-netflow/files/1351253/netflow.tar.gz)
