### ISSUE TITLE
Redis plugin as input

### ISSUE THREAD

**Issue by PORN-FLAKES** [logstash-plugins/logstash-codec-netflow#99]
Hello, this is not an issue and more like a brainstorm question, but I doubt someone else would be able to answer this except the developers of this codec themselves. All the examples including this codec use UDP plugin as input and I was wondering could I use Redis plugin as input? To be honest I have written my own codec using yours as an example because in my case is we are not using Netflow but Huawei DataFlow instead, but those two are kinda similar. So I got the codec working with UDP input, but am unable to run it with Redis even tho Redis claims that they are able to store binary safe strings. Any thoughts?

**Comment by jorritfolmer** [comment]
For my understanding:

- you found a way to get the Huawei dataflow into redis
- are pulling these out of redis again with logstash-input-redis
- and want to decode them with your logstash-codec-huaweidataflow?

I would first find out where the difference is at in the packets you pull out of redis versus what goes into redis. Perhaps Redis considers the data to be finished after encountering the first null character in the huawei datagrams. Or perhaps the input plugin finishes reading afer the first null terminated string?

**Comment by jorritfolmer** [comment]
Closing due to lack of response.

**Comment by PORN-FLAKES** [comment]
Sorry for the lack of response but basically I have figured out what was the problem. First, I was using rsyslog to push data to redis but even tho redis supports binary safe strings they have to be pushed in a specific way and rsyslog redis module just pushes binary data as simple string and that was causing packet corruption. Second, after I figured out the rsyslog issue by writing my own socket to redis java application there was a problem that packets that come from redis were bigger due to redis adding some additional information (its own header if you can say that) like storage key name and so on. So after all that I just added some byte skipping to skip all the stuff that redis added at the begining of the packets and it works. I am just writing this here if by any chance someone else have questions like these :) To be clear I am using Redis as a queue mechanism because my traffic have highs and lows depending on time of the day so advanced queues help to even it out during the 24 hours and logstash UDP input plugin is very limited when it comes to queues not to mention monitoring.

**Comment by jorritfolmer** [comment]
Thank for the details!
